### ISSUE TITLE
Remove 711.ua related information from templates

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#106]
We have a lot of stored 711.ua information stored in templates.
We should remove them and make possible to pass this information at the moment of booking.

**Comment by Smotrov** [comment]
[Strange](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Air/templates/AIR_CREATE_RESERVATION_REQUEST.xml#L28).
