### ISSUE TITLE
Return importPnr response as object

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#113]
At the time being response of the `importPnr` request is returned as `Array`, but I've found that in all inner calls that data is now just used as `pnrData[0]` (in `ticket` and `getTickets`).

I think it's confusing and we have to replace it with just an object.

@Smotrov, @shmuga, @articice, what do you think?

**Comment by articice** [comment]
`importPNR` uses the `extractBookings` parser to fetch reservations (bookings) out of a Universal Record. One UR can have many bookings, so there's no error in this part.

Your observation shows one of the basic assumptions built into uapi-json - we always create only one reservation (booking) per UR and treat GDS bookings as if they are Universal Records and vice-versa. Booking, import and cancel operations are simplified and **rely on this assumption**.

From the external API, user can only import reservations by their PNRs into URs; the uapi-json behavior is not defined for URs that have been externally modified to contain more than one booking and may cause errorneous behavior (like - cancel all bookings from UR group when cancel of one has been requested).

The feature of putting combined OW2RT bookings into one UR has not been developed and is now superceded by an identical feature from Travelport. Perhaps, we should discuss this feature too.

**Comment by dchertousov** [comment]
I think we should return information about the PNR we passed as param only, even if the UR contains more then 1 PNR. Because otherwise we can fail in some calls (like `ticket`).

Other PNRs of the UR could be easily retrieved with other API calls.
We should plan to add something like `getUR`.

**Comment by articice** [comment]
Yes, I agree. 

If the UR contains more than one PNR, we should return the object for currently requested PNR only.
This way, the internal method would return all bookings as array, and then `importPnr` would choose the correct item to return from this array.

And yes, we can create another method `getUR`, which would expose the bare internal method.

**Comment by dchertousov** [comment]
I propose following methods to be implemented:
- `getUniversalRecordByPNR` - returns all the data we were able to parse from UR including all the PNRS inside one UR
- `getPNR` - returns the PNR which was requested
- `importPNR` - keep for backwards compatibility until release of version 1.0.0, but it should return an array of the only element - PNR which was requested (in case if UR contains more than one and we are unsure of order), because it is still used by importPNRResult[0]

**Comment by dchertousov** [comment]
`getPNR` and `importPNR` in this case will be just a wrapper of the `getUniversalRecordByPNR` method, returning only part of the data

**Comment by dchertousov** [comment]
Closed by #196
