### ISSUE TITLE
Add lookup for PNR number and import PNR when ticket info is not fully available

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#124]
According to #114 , if PNR was not imported before `AirRetrieveDocumentReq` transaction is run then uAPI returns incomplete ticket data. In order to receive full data PNR must be imported first.

Proposed is following mechanism of retrieving that data:

1. Retrieve ticket data with `AirRetrieveDocumentReq`
1. Check data for completeness (checking for PNR locator)
1. If data is complete return it to user
1. If data is not complete make request with `TerminalService` to get PNR (`getPNRByTicketNumber` method of `AirService`)
1. Import PNR to uAPI
1. Get ticket data once again
1. Return ticket data

If on any step error is occurred - error is returned.
When error is occurred for a single ticket while executing `getTickets` error is returned.

**Comment by Smotrov** [comment]
Please make a couple of tests with thickets that has PNR which is already in history.

**Comment by dchertousov** [comment]
We can't yet fully rely on the processed described above as an issue found in some cases. Details are in  #125

**Comment by Smotrov** [comment]
For the time being, let's just reply with error, that _module doesn't support processing of booking with no active segments. Yet._  Because it seems like uAPI restriction. Once we will find some workaround we will remove this message.

**Comment by Smotrov** [comment]
It would also be useful if in this case we would also add ticket information in terminal text format. 
This functional should be deactivated by default in order to avoid errors for those who doesn't have terminal enabled credentials. Enabling should be possible through settings.

**Comment by dchertousov** [comment]
Error will be thrown.
Could be changed in further versions.
