### ISSUE TITLE
Can't get tickets from cancelled PNRs

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#125]
AS discussed in #114, if PNR was not imported to uAPI, there’s no way to get full ticket information from tickets related to this PNR.

As a workaround we discussed to get PNR from `*TE/XXX` command, then import it, and then get ticket data via normal `AirRetrieveDocumentReq` request.

But during import of some PNRs I've discussed following issue: if the PNR has no active segments, then it's impossible to import it into uAPI as I receive the following message from uAPI:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>No provider reservation to import.</faultstring>
      <detail>
        <common_v36_0:ErrorInfo xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0">
          <common_v36_0:Code>13003</common_v36_0:Code>
          <common_v36_0:Service>URSVC</common_v36_0:Service>
          <common_v36_0:Type>Business</common_v36_0:Type>
          <common_v36_0:Description>No provider reservation to import.</common_v36_0:Description>
          <common_v36_0:TransactionId>03E780E40A0759C2120A1D99DB325B47</common_v36_0:TransactionId>
          <common_v36_0:TraceId />
        </common_v36_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
```

Therefore, right now there is no other way to retrieve ticket pricing information, but from Terminal.

Does anyone know a workaround for this?

**Comment by Smotrov** [comment]
So basically the question is: "_How to retrieve full ticket information in uAPI from PNR that doesn't have any active segments_"?

**Comment by dchertousov** [comment]
@Smotrov yes

**Comment by Smotrov** [comment]
Please try to add passive segment before importing PNR.

**Comment by dchertousov** [comment]
Also importPNR should be fixed, as it returns now error with no active segments present.

**Comment by dchertousov** [comment]
As far, as I understand, adding passive segments through uAPI is possible only, when PNR is imported, so it has to be done via `TerminalService`. Is that right?

**Comment by shmuga** [comment]
Yep, looks like you are right. Cause you need to make UniversalRecordModify request which requires LocatorCode from UR.

**Comment by ferdinand-valderrama-bcs** [comment]
how did this issue got resolved? Can anyone help me? I'm quite new to doing uAPI cancellation thank you

**Comment by creduo** [comment]
@ferdinand-valderrama-bcs It has been resolved by adding a temporary segment and canceling pnr using terminal commands. You can find the code in getUniversalRecordByPNR, src/Sesrvices/Air/Air.js

**Comment by ferdinand-valderrama-bcs** [comment]
okay thanks!
