### ISSUE TITLE
Inconsistent request and response passenger type.

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#135]
During booking request passengers have next shape:
```
{
          lastName: 'TRAVELER',
          firstName: 'IVAN',
          passCountry: 'UA',
          passNumber: 'ES221731',
          birthDate: '19680725',
          gender: 'M',
          ageCategory: 'ADT',
}
```

But in response to `importPNR` request we return next shape:

```
{
  "lastName": "TRAVELER",
  "firstName": "IVAN",
  "passCountry": "UA",
  "passNumber": "ES221731",
  "birthDate": "25Jul68",
  "ageType": "ADT",
  "gender": "M",
  "uapi_ref_key": "6UwyfoBAAA/BO0yVFBAAAA=="
}
```

Proposition to make them the same to make response reusable.

**Comment by dchertousov** [comment]
+1

**Comment by dchertousov** [comment]
@shmuga I can take this issue to include in 0.8.0

**Comment by shmuga** [comment]
I'm already working on it. Will make this changes in PR with ExchangeQuote request.

**Comment by shmuga** [comment]
Changed date format in https://github.com/Travelport-Ukraine/uapi-json/pull/146/commits/770bd28d2f25e49a80f6859dbc9cd9ceb6fc4ec9

**Comment by shmuga** [comment]
Fixed in https://github.com/Travelport-Ukraine/uapi-json/pull/162/commits/a7fb5c0af586438ce7359685236342cccd997bb9
