### ISSUE TITLE
Terminal instance has READY state before finished executing commands

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#138]
@shmuga , please have a look:
 - [Here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Terminal/Terminal.js#L95) we mark Terminal as ready
 - And [here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Terminal/Terminal.js#L104) we process response

But if response contains `MORE` symbol, we send `MD` commands to get the rest.

The question is: don't we need to replace an order of this two commands?

**Comment by shmuga** [comment]
Yes for sure, it can cause race condition.

**Comment by dchertousov** [comment]
Ok, I'll fix it.
Also I'll try to cover state logic for `TerminalService`
