### ISSUE TITLE
Error parsing segments in importPNR

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#141]
Possibly connected with the only segment in booking.

Example: `7j8j/3VPFQQ`

**Comment by shmuga** [comment]
It's better to attach sample of response xml

**Comment by dchertousov** [comment]
XML is clear:
[importPNRResponse.xml.txt](https://github.com/Travelport-Ukraine/uapi-json/files/776555/importPNRResponse.xml.txt)

Parsed response:
[importPNRParsedResponse.json.txt](https://github.com/Travelport-Ukraine/uapi-json/files/776556/importPNRParsedResponse.json.txt)

Final response:
[importPNRFinalResponse.json.txt](https://github.com/Travelport-Ukraine/uapi-json/files/776563/importPNRFinalResponse.json.txt)

**Comment by dchertousov** [comment]
Looks like `importPNR` requires `air:AirPricingInfo` for returning trips.
Tak a look [here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Air/AirParser.js#L602) and [there](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Air/AirParser.js#L577).

Which means returning trips requires fare quotes to be created.

I find this behavior a bit strange.

@shmuga , @articice , @Smotrov , your suggestions?

**Comment by shmuga** [comment]
I think it has such behavior because airCreateReservation makes FQ.

Maybe let's make a fallback for segments if there is no pricingInfo?

**Comment by dchertousov** [comment]
When you import PNR, not made by `uapi-json` calls you never know if it has reservation or not.
I think trips should be parsed directly from `air:AirSegment` and then only **extended** if possible from reservations. Or maybe we should leave reservations just as separate entity.

**Comment by shmuga** [comment]
I agree. Let's parse them from `air:AirSegment` for better integration with terminal bookings.

**Comment by dchertousov** [comment]
`fareBasisCode` has to be removed from `trips` along with baggage, as for two different passengers in booking two different reservations could be created in different classes with different baggage allowance and `fareBasisCode`

**Comment by shmuga** [comment]
Moving ticket to 0.8.0?

**Comment by articice** [comment]
@shmuga yes

**Comment by shmuga** [comment]
Closed with #145
