### ISSUE TITLE
The Provider reservation is being modified externally. Please Air Ticket later.

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#147]
When someone opens BF in terminal after uapi booking transaction - ticketing is blocked for some time. And each try of doing ticketing request will cause this error.

To avoid this problem I suggest to make `importPnr` request before each ticketing and pass `Version` number to ticketing request. Similar logic is already implemented in case if FOID is needed for ticketing.

**Comment by articice** [comment]
@shmuga unfortunately, the ticketing request does not accept `Version`, because unlike setting FOID, it's not defined as a Universal Record modify operation in WSDL.

**Comment by articice** [comment]
I have implemented an exponential back-off for ticketing retries, including an optimized scenario for FOID and then a ticketing retry.

**Comment by dchertousov** [comment]
Closed by #299
