### ISSUE TITLE
Format inconsistency

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#148]
After updating lowFareSearch format seems to be not fully compatible with other transactions.

As @shmuga  admitted, changes are as follows:

- [ ] missing fareBasis for trips (required for booking)
- [ ] plane and duration fields are arrays, not strings

In my opinion, plane and duration should be arrays, as they reflect planes and flight durations for technical segments, as planes may be changed.

As for fareBasis, is there any situation, when fareBasis is different for different passengers? How do we handle such situations?

**Comment by shmuga** [comment]
I thinks it's tightly connected with #135 also.

**Comment by dchertousov** [comment]
Just to note, plane/duration/baggage fields are updated in this way to reflect possible plane changes during technical stops and actual time in the air on air technical segments.

As I checked, booking process going well with plane/duration/baggage as arrays.

@shmuga , do you have any complaints about them?
