### ISSUE TITLE
Parse Response to JSON

### ISSUE THREAD

**Issue by donpeter** [Travelport-Ukraine/uapi-json#211]
How can I Parse the data response to JSON. I don't really understand the response I am getting from the API . Please can any one provide a parser function? thank you

**Comment by dchertousov** [comment]
Hello @donpeter. Could you please paste the response you receive?

**Comment by donpeter** [comment]
@dchertousov Thanks, The response was parsed. I was looking at the wrong data

**Comment by donpeter** [comment]
But is there any way I can do an advance search like changing the currency
