### ISSUE TITLE
Advance Search

### ISSUE THREAD

**Issue by donpeter** [Travelport-Ukraine/uapi-json#212]
How can I perform an advance search? Like change of Currency or Preferred Carriers

**Comment by shmuga** [comment]
Hello @donpeter 
All currently supported params for search you can find here https://github.com/Travelport-Ukraine/uapi-json/blob/master/docs/Air.md#shop

Alson take a look at examples folder https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Air/shop.js

**Comment by shmuga** [comment]
Did it help @donpeter ?

**Comment by donpeter** [comment]
Yeah it help, I edit  the  src/build/service/AIR_LOW_FARE_SEARCH_REQUEST.handlebars.js to the belo code.
"use strict";

module.exports = `



<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <air:LowFareSearchReq
            AuthorizedBy="user" TraceId="{{requestId}}" TargetBranch="{{TargetBranch}}"
            ReturnUpsellFare="true"
            xmlns:air="http://www.travelport.com/schema/air_v33_0"
            xmlns:com="http://www.travelport.com/schema/common_v33_0"
            >
            <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
            {{#legs}}
            <air:SearchAirLeg>
                <air:SearchOrigin>
                    <com:CityOrAirport Code="{{from}}" PreferCity="true"/>
                </air:SearchOrigin>
                <air:SearchDestination>
                    <com:CityOrAirport Code="{{to}}" PreferCity="true"/>
                </air:SearchDestination>
                <air:SearchDepTime PreferredTime="{{departureDate}}"/>
                <air:AirLegModifiers>
                    {{#if ../cabins}}
                    <air:PreferredCabins>
                        {{#each ../cabins}}
                        <com:CabinClass Type="{{this}}"/>
                        {{/each}}
                    </air:PreferredCabins>
                    {{/if}}
                </air:AirLegModifiers>
            </air:SearchAirLeg>
            {{/legs}}
            <air:AirSearchModifiers {{#if MaxJourneyTime}} MaxJourneyTime="{{MaxJourneyTime}}" {{/if}}>
                <air:PreferredProviders>
                    <com:Provider Code="1G" xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
                </air:PreferredProviders>
            </air:AirSearchModifiers>
            {{#passengers}}
            <com:SearchPassenger Code="{{ageCategory}}"{{#if child}} Age="9"{{/if}} xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
            {{/passengers}}
            {{#if pricing}}
            <air:AirPricingModifiers CurrencyType="{{pricing.currency}}" {{#if ETicketability}} ETicketability="{{pricing.ETicketability}}"{{/if}} />
            {{/if}}
            {{#if emulatePcc}}
            <air:PCC>
                <com:OverridePCC ProviderCode="1G" PseudoCityCode="{{emulatePcc}}"/>
            </air:PCC>
            {{/if}}
            
        </air:LowFareSearchReq>
    </soap:Body>
</soap:Envelope>
`;

So now within the request I can pass more params like this
const params = {
	  legs: [
	    {
	      from: 'LOS',
	      to: 'IST',
	      departureDate: '2017-07-09'
	    },
	    {
	      from: 'IST',
	      to: 'LOS',
	      departureDate: '2017-08-08'
	    }
	  ],
	  passengers: {
	     ADT: 1,
	     /*
	      CNN:1,
	      INF: 1,
	      INS: 1, //infant with a seat
	      */
	   },
	  cabins: ['Economy'], // ['Business'],
	  requestId: '4e2fd1f8-2221-4b6c-bb6e-cf05c367cf69',
	  MaxJourneyTime: 13, //Any Integer
	  pricing: {
	  	currency: 'USD',
	  	//ETicketability: 'Yes', //'No'
	  }
	  
	};

And it works.

**Comment by shmuga** [comment]
@donpeter Wow! Awesome improvement. It would be really nice if you'll add it to this lib.

Please check this file for information how to do that https://github.com/Travelport-Ukraine/uapi-json/blob/master/CONTRIBUTING.md

Also, it's better to name `MaxJourneyTime` as `maxJourneyTime`. Same situation with `ETicketability` to be `eTicketability`. 

If you have any questions about the development process, feel free to ask.

**Comment by iplanwebsites** [comment]
@shmuga, It seems like @donpeter fix adds a very useful feature. Do you think it'd be possible to add it as part of the next update so we can all keep our modules free from home patches? 
Best,

**Comment by shmuga** [comment]
@iplanwebsites Yes, you also can easily follow contribution guide and try to add needed params. But If you have no possibility to do that I can try to resolve you issue by myself.

**Comment by iplanwebsites** [comment]
Thanks @shmuga!
This is a bit above my ability so your help would greatly be appreciated :)

**Comment by shmuga** [comment]
Landed in 0.15.6
