### ISSUE TITLE
AirService .book(param) Error

### ISSUE THREAD

**Issue by donpeter** [Travelport-Ukraine/uapi-json#216]
I am using a trial credential, I don't know if that is the problem.
When I try to book(book) an air service referencing the book.js example, I get the following response...
{
	"name": "ParsingError.AirParsingError",
	"data": {
		"faultcode": "Server.InvalidRequestException",
		"faultstring": "[Error] :10:69: cvc-enumeration-valid: Value 'Direct' is not facet-valid with respect to enumeration '[Seamless, DirectAccess, Basic]'. It must be a value from the enumeration.",
		"detail": {
			"ErrorInfo": {
				"Code": "1000",
				"Service": "WEBSVC",
				"Type": "Data",
				"Description": "Validation failed on request message.",
				"TransactionId": "EEEA97850A076478C608A543CDE04636",
				"Auxdata": {
					"Entry": {
						"Reason": "\nLastElement",
						"Description": "AirSegment InventoryRequestType=Direct"
					}
				},
				"xmlns": "http://www.travelport.com/schema/air_v36_0"
			}
		}
	}
}

And a Console response  of 

Response SOAP:  
<SOAP:Envelope
	xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<SOAP:Fault>
			<faultcode>Server.InvalidRequestException</faultcode>
			<faultstring>[Error] :10:69: cvc-enumeration-valid: Value 'Direct' is not facet-valid with respect to enumeration '[Seamless, DirectAccess, Basic]'. It must be a value from the enumeration.</faultstring>
			<detail>
				<ErrorInfo
					xmlns="http://www.travelport.com/schema/air_v36_0">
					<Code>1000</Code>
					<Service>WEBSVC</Service>
					<Type>Data</Type>
					<Description>Validation failed on request message.</Description>
					<TransactionId>EEEA97850A076478C608A543CDE04636</TransactionId>
					<Auxdata>
						<Entry>
							<Reason>
LastElement</Reason>
							<Description>AirSegment InventoryRequestType=Direct</Description>
						</Entry>
					</Auxdata>
				</ErrorInfo>
			</detail>
		</SOAP:Fault>
	</SOAP:Body>
</SOAP:Envelope>
Parsed error response {"SOAP:Fault":[{"faultcode":["Server.InvalidRequestException"],"faultstring":["[Error] :10:69: cvc-enumeration-valid: Value 'Direct' is not facet-valid with respect to enumeration '[Seamless, DirectAccess, Basic]'. It must be a value from the enumeration."],"detail":[{"ErrorInfo":[{"$":{"xmlns":"http://www.travelport.com/schema/air_v36_0"},"Code":["1000"],"Service":["WEBSVC"],"Type":["Data"],"Description":["Validation failed on request message."],"TransactionId":["EEEA97850A076478C608A543CDE04636"],"Auxdata":[{"Entry":[{"Reason":["\nLastElement"],"Description":["AirSegment InventoryRequestType=Direct"]}]}]}]}]}]}

**Comment by shmuga** [comment]
I think it's problem described in https://github.com/Travelport-Ukraine/uapi-json/issues/77#issuecomment-261069489 and it is still not fixed. Could you please try to change from Direct to DirectAccess property in AirPrice request template?

Related issues #220

**Comment by donpeter** [comment]
@shmuga  thanks that helped to fix that error, but I get a different error afterwards

{
    "name": "RuntimeError.AirRuntimeError",
    "data": {
        "faultcode": "Server.System",
        "faultstring": "Transaction Error: Procedure/5012",
        "detail": {
            "common_v36_0:ErrorInfo": {
                "common_v36_0:Code": "10",
                "common_v36_0:Service": "SYSTEM",
                "common_v36_0:Type": "System",
                "common_v36_0:Description": "Transaction failure.",
                "common_v36_0:TransactionId": "F41643D30A076477D20CB0817341B6FC",
                "common_v36_0:TraceId": "",
                "xmlns:common_v36_0": "http://www.travelport.com/schema/common_v36_0"
            }
        }
    }
}

i don't understand what went wrong. Please is there any place at TravelPort documentation where I can easily find and read about such errors to understand better. Thanks for your help so far.

**Comment by shmuga** [comment]
@donpeter I'm not sure about last error. You should write in Travelport support system to ask what goes wrong.
