### ISSUE TITLE
Replace error handling with node-error-helpers

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#23]
Custom errors handling should be replaced with node-error-helpers to stop using current error handling as complicated and lacking inheritance.

- [x] Replace errors handling
- [x] Move errors classes to each service
- [x] Common errors stay in the root
- [x] Check for errors usages
- [x] Reflect new error handling system in docs

**Comment by dchertousov** [comment]
Done

**Comment by dchertousov** [comment]
error no check should be replace with instanceof checks in Services

**Comment by shmuga** [comment]
@dchertousov  I think we forgot to mention this changes in docs.
It would be nice to document error types and mention about lib that generates them.

**Comment by dchertousov** [comment]
@shmuga could you please review the code once again and make appropriate changes in docs?

**Comment by dchertousov** [comment]
New errors handling system reflected in docs with examples
