### ISSUE TITLE
AirService.fareRules() request

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#266]
Colleagues, for a new front-end functionality request from our partners, I've migrated some old code into uapi-json for a `fareRules` request.

Just like `book`, it receives a list of segments (taken from a previous `shop` reply, **with or without farebasis**) and a long/short param. It performs an AirPriceRequest to look up such flight combination and returns sets of fare rules that apply, associated with each `FareInfoRef` for such a quotation.

Will create PR soon, it will need some code prettify and test coverage. It reuses many validators from existing internal AirPriceReq, and the segments validator from `book`, and we can refactor those using `Joi` which was added as a dependency in the latest version.

**Comment by Smotrov** [comment]
👍
