### ISSUE TITLE
restrictWaitlist param for .book()

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#267]
I've added a `restrictWaitlist` boolean param to `book`.
Plus, some additional error parsing code in case of waitlisting.

Will create PR soon.

**Comment by dchertousov** [comment]
Please describe this param.
What it is used for?

**Comment by dchertousov** [comment]
Decided to rename param to `allowWaitlist` in order to stay away from waitlisted segments in booking by default.
