### ISSUE TITLE
Export ServiceErrors alongside with other errors

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#270]
Service error from `src/error-types.js`
should be exported in 
`src/index.js`

**Comment by articice** [comment]
which requests does this relate to?

**Comment by dchertousov** [comment]
@articice see updated description

**Comment by articice** [comment]
@dchertousov this errors list is exported as `errors.Common.ServiceErrors` from src/index.js

error-types.js is included as `commonErrors`
```javascript
const commonErrors = require('./error-types');
```
and the whole object is exported as `errors.Common` in src/index.js

I don't see what else has to be done.

**Comment by articice** [comment]
`errors.Common.ServiceError` list and any of its children are not imported anywhere, but their closest neighbour `errors.Common.ValidationError` is mentioned in [README usage example](https://github.com/Travelport-Ukraine/uapi-json/blame/master/README.md#L51).
