### ISSUE TITLE
Fix incorrect parsing of endorsement.

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#276]
Now `endorsement` field in `fareQuotes` is resolved from incorrect place. It's parsed from ticketing modifiers but should from fq fareInfo.

**Comment by dchertousov** [comment]
Have you tried a case when FQ is removed from PNR?

**Comment by shmuga** [comment]
I asked out internal support and they said that ticketing endorsement and fq endorsement are different things. And it's important for us to resolve it for not deleted fq-s for now.

**Comment by shmuga** [comment]
Fixed in #277
