### ISSUE TITLE
Passing extra params to methods

### ISSUE THREAD

**Issue by iplanwebsites** [Travelport-Ukraine/uapi-json#283]
Quick question: How is it possible to pass parameters documented in the models to the wrapper functions.

For example, starting from the [Air.shop](https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Air/shop.js) example, I'm trying to set a [custom currency](https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Pricing/Air_Pricing.htm).

**Comment by shmuga** [comment]
I've added this issue to next milestone.

**Comment by iplanwebsites** [comment]
Thanks a lot @shmuga!
Just tested and it seems to work perfectly for the currency!

Do you know who would be the best person to talk if I have technical questions around implementation? I'm getting a lot of inconsistent failures from the API (for the exact same request) and I'm trying to troubleshoot the problem.
