### ISSUE TITLE
How to start ??

### ISSUE THREAD

**Issue by eig0r** [Travelport-Ukraine/uapi-json#291]
i'm using Travelport Universal API · GitHub for php
i want to work with Java script 
so please how can i start use uapi-jason??
can any one help?

**Comment by shmuga** [comment]
Hello @eig0r !
Did you look into README?

**Comment by Smotrov** [comment]
Yes you can! 
See details [here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/README.md).

**Comment by eig0r** [comment]
I'm sorry if i don't understand but really i need some help on the road i did ( npm install --save uapi-json )
and i have Travel-port Credential 
i'm asking about 
1- where i put my Credential
2- how i found or get the result

i'm sorry again

**Comment by shmuga** [comment]
@eig0r try to look into examples folder https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Air/shop.js

Replace `testconfig` with your credentials in relevant format.

**Comment by eig0r** [comment]
thanks @shmuga  for support i get the following ( can you help please? )

eigor@eigor-pc:~/Desktop/uapi-json-master/examples/Air$ node shop.js 
/home/eigor/Desktop/uapi-json-master/src/Services/Hotels/HotelsService.js:1
(function (exports, require, module, __filename, __dirname) { import validateServiceSettings from '../../utils/validate-service-settings';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/eigor/Desktop/uapi-json-master/src/index.js:1:90)

**Comment by dchertousov** [comment]
@eig0r have you ever used npm?
You need to install uapi-json into your project as dependency using `npm install uapi-json`.
Then you have to import library and write the code, that will be using its methods.

If you never used the node.js, I think it's a good place to start: https://nodejs.org/en/docs/guides/getting-started-guide/

If you are familiar with node.js, you must note, that library itself is written in modern syntax, and while publishing into npm this code gets transpired to support current and older versions.

Please, feel free to open the issue while having issues with library itself, not nodes dependencies and imports.

**Comment by eig0r** [comment]
thanks for replay now i'm facing the following 
when i use the same credential in php i get result when i use uapi-json  i get the following response  

Input params  {
  "legs": [
    {
      "from": "LWO",
      "to": "JKT",
      "departureDate": "2018-07-18"
    },
    {
      "from": "JKT",
      "to": "IEV",
      "departureDate": "2018-07-21"
    }
  ],
  "passengers": {
    "ADT": 1
  },
  "cabins": [
    "Economy"
  ],
  "requestId": "4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60"
}
Request URL:  https://emea.universal-api.travelport.com/B2BGateway/connect/uAPI/AirService
Request XML:  



<soap:Envelope 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:LowFareSearchReq
            AuthorizedBy="user" TraceId="4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60" TargetBranch="P7086060"
            ReturnUpsellFare="true"
            
      xmlns:air="http://www.travelport.com/schema/air_v33_0"
            
      xmlns:com="http://www.travelport.com/schema/common_v33_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="LWO" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="JKT" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2018-07-18"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="JKT" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="IEV" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2018-07-21"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
            >
        <air:PreferredProviders>
          <com:Provider Code="1G" 
            xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
          </air:PreferredProviders>
        </air:AirSearchModifiers>
        <com:SearchPassenger Code="ADT" 
          xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
        </air:LowFareSearchReq>
      </soap:Body>
    </soap:Envelope>

Error Response SOAP:  {
  "status": 401,
  "data": {
    "errors": {
      "error": {
        "status": "76",
        "code": "Authentication Result Error Message Response  (76): Authentication credentials are invalid.",
        "detail": "Authentication Result Error Message Response  (76): Authentication credentials are invalid."
      }
    }
  }
}
{ RequestSoapError.SoapRequestError: Error during request to SOAP API. Check url validity
    at _axios2.default.request.then.catch.e (/home/eigor/Desktop/test3/node_modules/uapi-json/build/Request/uapi-request.js:105:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'RequestSoapError.SoapRequestError',
  data: { status: 401, data: { errors: [Object] } } }


may you advice?

**Comment by dchertousov** [comment]
@eig0r it looks, like you have issues with your credentials or with a way you put them into config

**Comment by shmuga** [comment]
@eig0r This also can be cause if you have pre-production credentials, don't you?

**Comment by eig0r** [comment]
i put the credentials like below

module.exports = {
  username: 'Universal API1/uAPI7493860511-a3805dc9',
  password: '########',
  targetBranch: 'P7086060',
  pcc: '8YC2',
};

and i use it in meteor project like below 
HTTP.call( 'POST','https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/HotelService', {

        auth: 'Universal API/uAPI7493860511-a3805dc9:#######',
        headers: {
            SOAPTarget: 'https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/HotelService',
            SOAPAction: 'http://required-namespace.com/methodName',

            'Content-Type': 'text/xml'
        },

        content: '<?xml version="1.0" encoding="utf-8"?>' +
                     '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ' +
                                    'xmlns:xsd="http://www.w3.org/2001/XMLSchema" ' +
                                    'xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
                       '<soap:Body> ' +
                         '<hot:HotelSearchAvailabilityReq xmlns:com="http://www.travelport.com/schema/common_v29_0" xmlns:hot="http://www.travelport.com/schema/hotel_v29_0" AuthorizedBy="user" TargetBranch="P7086060" TraceId="trace">' +
                            '<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>' +
                            '<hot:HotelSearchLocation>' +
                         '<hot:HotelLocation Location="DXB"/>' +
                         '</hot:HotelSearchLocation>' +
                         '<hot:HotelSearchModifiers NumberOfAdults="1">' +
                         '<com:PermittedProviders>' +
                         '<com:Provider Code="1G"/>' +
                         '</com:PermittedProviders>' +
                         '</hot:HotelSearchModifiers>' +
                         '<hot:HotelStay>' +
                         '<hot:CheckinDate>2017-11-18</hot:CheckinDate>' +
                         '<hot:CheckoutDate>2017-11-20</hot:CheckoutDate>' +
                         '</hot:HotelStay>' +
                         '</hot:HotelSearchAvailabilityReq>' +

                       '</soap:Body> ' +
                     '</soap:Envelope>'

      },
So what i'm doing wrong?

**Comment by dchertousov** [comment]
Could you please try omitting `pcc` attribute?
I believe, it's used for SVCB credentials only.

**Comment by eig0r** [comment]
i omitting pcc attribute
and same result
Error Response SOAP:  {
  "status": 401,
  "data": {
    "errors": {
      "error": {
        "status": "76",
        "code": "Authentication Result Error Message Response  (76): Authentication credentials are invalid.",
        "detail": "Authentication Result Error Message Response  (76): Authentication credentials are invalid."
      }
    }
  }
}

**Comment by eig0r** [comment]
@shmuga  yes i i have per-production certificate is that a problem?

**Comment by shmuga** [comment]
@eig0r You probably missed production: false flag. See https://github.com/Travelport-Ukraine/uapi-json/blob/master/README.md#settings-object
