### ISSUE TITLE
Integration in my project

### ISSUE THREAD

**Issue by trsorsimo96** [Travelport-Ukraine/uapi-json#303]
i have any problems

Failed to compile.

./node_modules/isemail/lib/index.js Module not found: Error: Can't resolve 'dns' in '/Users/tresordjoko/Downloads/ngx-admin-master/node_modules/isemail/lib' @ ./node_modules/isemail/lib/index.js 5:12-26 @ ./node_modules/joi/lib/types/string/index.js @ ./node_modules/joi/lib/index.js @ ./node_modules/uapi-json/build/Services/Air/validators/fop-credit-card.js @ ./node_modules/uapi-json/build/Services/Air/validators/index.js @ ./node_modules/uapi-json/build/Services/Air/AirValidator.js @ ./node_modules/uapi-json/build/Services/Air/AirService.js @ ./node_modules/uapi-json/build/Services/Air/Air.js @ ./node_modules/uapi-json/build/index.js @ ./src/app/app.module.ts @ ./src/main.ts @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by trsorsimo96** [comment]
./~/handlebars/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/tresordjoko/Downloads/angular2-seed-master/node_modules/handlebars/lib'
 @ ./~/handlebars/lib/index.js 17:11-24
 @ ./~/uapi-json/build/Request/uapi-request.js
 @ ./~/uapi-json/build/Services/Hotels/HotelsService.js
 @ ./~/uapi-json/build/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
client:119
./~/isemail/lib/index.js
Module not found: Error: Can't resolve 'dns' in '/Users/tresordjoko/Downloads/angular2-seed-master/node_modules/isemail/lib'
 @ ./~/isemail/lib/index.js 5:12-26
 @ ./~/joi/lib/types/string/index.js
 @ ./~/joi/lib/index.js
 @ ./~/uapi-json/build/Services/Air/validators/fop-credit-card.js
 @ ./~/uapi-json/build/Services/Air/validators/index.js
 @ ./~/uapi-json/build/Services/Air/AirValidator.js
 @ ./~/uapi-json/build/Services/Air/AirService.js
 @ ./~/uapi-json/build/Services/Air/Air.js
 @ ./~/uapi-json/build/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts
client:119
./~/joi/lib/types/string/index.js
Module not found: Error: Can't resolve 'net' in '/Users/tresordjoko/Downloads/angular2-seed-master/node_modules/joi/lib/types/string'
 @ ./~/joi/lib/types/string/index.js 5:12-26
 @ ./~/joi/lib/index.js
 @ ./~/uapi-json/build/Services/Air/validators/fop-credit-card.js
 @ ./~/uapi-json/build/Services/Air/validators/index.js
 @ ./~/uapi-json/build/Services/Air/AirValidator.js
 @ ./~/uapi-json/build/Services/Air/AirService.js
 @ ./~/uapi-json/build/Services/Air/Air.js
 @ ./~/uapi-json/build/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts

**Comment by Smotrov** [comment]
Not related to uAPI JSON

**Comment by shmuga** [comment]
@trsorsimo96 The problem is module is not available for browsers for now. It supports only Node.
