### ISSUE TITLE
TRM for HotelService

### ISSUE THREAD

**Issue by coding-artists** [Travelport-Ukraine/uapi-json#309]
This is not an issue actually, but a request to include TRM provider for HotelService in order to use also TRM city codes to search for hotels and not only IATA/Airport codes.

It would be awesome. Thanks

**Comment by shmuga** [comment]
Hello @coding-artists, 

Actually we already support TRM hotel codes. Please look [here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Hotels/search.js#L14) to see how to use it.
