### ISSUE TITLE
request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by coding-artists** [Travelport-Ukraine/uapi-json#311]
I'm trying to use the library within a reactjs. When I try to make a request to AirService I get this error. 

Failed to load https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example.com' is therefore not allowed access. The response had HTTP status code 500.

**Comment by dchertousov** [comment]
Hello @coding-artists.

uapi-json wasn't created to be used in browser environment.
you have to rely on some backend, as Travelport does not accept XSS calls from browsers
