### ISSUE TITLE
cannot retrieve TargetBranch information for TargetBranchCode1G

### ISSUE THREAD

**Issue by skills-up** [Travelport-Ukraine/uapi-json#322]
Hi,

I'm using the latest release 0.18.3. When I'm trying to make a request similar to shop.js example, I'm getting the following error:
```
{ RuntimeError.AirRuntimeError: Air service runtime error
    at Parser.AirErrorHandler (/Users/gaurav/node_modules/uapi-json/build/Services/Air/AirParser.js:292:31)
    at validateSOAP (/Users/gaurav/node_modules/uapi-json/build/Request/uapi-request.js:132:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'RuntimeError.AirRuntimeError',
  data: 
   { faultcode: 'Server.AuthenticationException',
     faultstring: 'cannot retrieve TargetBranch information for TargetBranchCode1G',
     detail: { 'common_v33_0:ErrorInfo': [Object] } } }
```
I'm getting the same error for other Target Branches (such as 1P) as well. Could you please let me know if I've missed something?

Here is the debug info:
Input params: 
```
{
  "legs": [
    {
      "from": "DEL",
      "to": "BOM",
      "departureDate": "2018-07-18"
    }
  ],
  "passengers": {
    "ADT": 1
  },
  "cabins": [
    "Economy"
  ],
  "requestId": "4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60",
  "pricing": {
    "currency": "INR"
  }
}
```
Request URL:
` https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService `

**Comment by dchertousov** [comment]
@skills-up please enable debug level 2 in settings and provide us with the XML, which is sent to to Travelport.

**Comment by skills-up** [comment]
Request XML:  
```
<!--Release 33-->
<!--Version Dated as of 14/Aug/2015 18:47:44-->
<!--Air Low Fare Search For Galileo(1G) Request-->
<soap:Envelope 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:LowFareSearchReq
            AuthorizedBy="user" TraceId="4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60" TargetBranch="1G"
            ReturnUpsellFare="true"
            
      xmlns:air="http://www.travelport.com/schema/air_v33_0"
            
      xmlns:com="http://www.travelport.com/schema/common_v33_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="DEL" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="BOM" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2018-07-18"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
            >
        <air:PreferredProviders>
          <com:Provider Code="1G" 
            xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
          </air:PreferredProviders>
        </air:AirSearchModifiers>
        <com:SearchPassenger Code="ADT" 
          xmlns:com="http://www.travelport.com/schema/common_v33_0"/>
          <air:AirPricingModifiers
                CurrencyType="INR"

            />
        </air:LowFareSearchReq>
      </soap:Body>
    </soap:Envelope>
```

Response SOAP:
```
<SOAP:Envelope 
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.AuthenticationException</faultcode>
      <faultstring>cannot retrieve TargetBranch information for TargetBranchCode1G</faultstring>
      <detail>
        <common_v33_0:ErrorInfo 
          xmlns:common_v33_0="http://www.travelport.com/schema/common_v33_0">
          <common_v33_0:Code>-1</common_v33_0:Code>
          <common_v33_0:Service>AIRSEARCH_SERVICE</common_v33_0:Service>
          <common_v33_0:Type>AuthenticationException</common_v33_0:Type>
          <common_v33_0:Description>cannot retrieve TargetBranch information for TargetBranchCode1G</common_v33_0:Description>
          <common_v33_0:TransactionId>90397B1F0A0764774F621B2933C7C9D9</common_v33_0:TransactionId>
          <common_v33_0:TraceId>4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60</common_v33_0:TraceId>
        </common_v33_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
```

**Comment by dchertousov** [comment]
I was able to get response with my credentials and your input params.
I think you should contact your local Travelport/uapi support with your credentials and XML response and request to get further information.

**Comment by shmuga** [comment]
Also there is possibility that you have preproduction credentials. Please try set `production` flag to false.

**Comment by skills-up** [comment]
Well, I do have pre production credentials, and the production flag is set to false. When there is authentication problem, say I forget to set the production flag, or don't prefix Universal uAPI/ to the username then I get an authentication failure for credentials. So this is clearly a different issue.

**Comment by skills-up** [comment]
Further, I'm facing no such issue in PHP code. There I'm able to retrieve the flight options for the same leg without any issues. Although the XML format is a little different (taken from PHP low fare shopping sample code).
To top it all, the only reason I'm trying the json API only to benchmark the number of parallel users that can be served via node vis-a-vis nginx+php7. Just an LFS query and a db insert form the whole benchmark script. The benchmark results will help me in deciding which backend should I use. Has anyone run such a benchmark test already?

**Comment by skills-up** [comment]
I managed to solve the issue. I feel rather stupid for the whole thing.
Turned out that `targetBranch` value won't be `1G` but a different string in the format `XNNNNNN` which was being used by the PHP script. I am marking this issue as closed, and highlighting the resolution in case someone faces the same issue again.

**Resolution:**
`auth.targetBranch = 'P999999';`

**Comment by shmuga** [comment]
@skills-up Yes, `targetBranch` is part of your auth credentials provided for you by Travelport. Nice to hear that you have found the solution.

**Comment by sushrest** [comment]
@shmuga, 
Need your help. 
I have following error can you try with your credential and my input params?
```
const params = {
    legs: [
      {
        from: 'LWO',
        to: 'JKT',
        departureDate: '2018-11-28'
      },
      {
        from: 'JKT',
        to: 'IEV',
        departureDate: '2018-12-21',
      },
    ],
    passengers: {
      ADT: 1,
      /*
       CNN:1,
       INF: 1,
       INS: 1, //infant with a seat
       */
    },
    cabins: ['Economy'], // ['Business'],
    requestId: '4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60',
    maxJourneyTime: 300,
    pricing: {
      currency: 'USD',
      // eTicketability: true,
    },
  };
```
My credential format is
```
const settings:any = {
    auth: {
        username: 'Universal API/uAPI1344578770-c7803131',
        password: '******************',
        targetBranch: 'P7039109'
    },
    debug: 2,
    production: false,    
};
```

AirService request 
```
 let airService = uAPI.createAirService(settings);
  airService.shop(params)
  .then(
    res => sails.log(res),
    err => sails.log(err)
  );
```

Response:
```
Error Response SOAP:  {
  "status": 401,
  "data": "<SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:faultcode>76</SOAP-ENV:faultcode><SOAP-ENV:faultstring>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:faultstring><SOAP-ENV:faultactor>            </SOAP-ENV:faultactor><SOAP-ENV:detail>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>"
}
```

**Comment by dchertousov** [comment]
@skills-up I could confirm, that using our credentials we were able to get a successful response to the request you provided.

Have you tried setting `production` from `false` to `true`? Authentication fail could be caused by using production credentials on non-production environment.

**Comment by sushrest** [comment]
Hi @dchertousov, can you try with my param as well? I have production flag to false and my credential is for pre-prod
https://github.com/Travelport-Ukraine/uapi-json/issues/322#issuecomment-436395089

**Comment by dchertousov** [comment]
@sushrest with your exact params I get the same error as you, as credentials we have are production only.

**Comment by sushrest** [comment]
@dchertousov Could you send me the params that worked for you even on prod? Also the credentials i used are as follows: 
```
const settings:any = {
    auth: {
        username: 'Universal API/uAPI1344578770-c7803131',
        password: '******************',
        targetBranch: 'P7039109'
    },
    debug: 2,
    production: false,    
};
```
Can you verify if this is correct?

**Comment by dchertousov** [comment]
@sushrest 
I used your exact params just with my credentials and it worked.

I recommend you to check your credentials with your local Travelport authority, providing them with exact request and response XMLs.

Have a nice day.

**Comment by sushrest** [comment]
@dchertousov Many thanks for prompt response. Can you please if you know advice where can I get immediate support for this? I have been waiting for the response email since 20 hours.

**Comment by dchertousov** [comment]
@sushrest Unfortunately, there's no place to get immediate support for such cases.
