### ISSUE TITLE
Plan to addition of FlightService with FlightInformationReq

### ISSUE THREAD

**Issue by MiseCZ** [Travelport-Ukraine/uapi-json#33]
We are planning to add:

```
uAPI.createFlightService(settings) => FlightService
```

With usage like:

```
service.information(params) => Promise
```

Params should be:

```
{
    "airline": "KL",
    "flightNumber": "3098",
    "departure": "2016-10-21"
}
```

Response:

```
{
  "from": "LHR",
  "to": "JFK",
  "departure": "2016-10-21T14:00:00.000+01:00',
  "arrival": "2016-10-21T16:40:00.000-04:00",
  "duration": "PT7H40M",
  "plane": "789",
  "fromTerminal": "3",
  "toTerminal": "4"
}
```

Would that be ok with you or would you suggest otherwise?

**Comment by shmuga** [comment]
Yes! Great idea!
But currently, we are planning to do some refactoring and change some files/code structure.
Look to this [milestone](https://github.com/Travelport-Ukraine/uapi-json/issues/25).
After that, I think you can easily add this Service. 
Also, we are going to provide some Core Api docs and contributing instructions to that time.
Stay tuned!

p.s I think we'll do that till 24 October.

**Comment by dchertousov** [comment]
@MiseCZ What else are you planning to add into FlightService in future?

**Comment by jirismika** [comment]
@dchertousov AFAIK, at this moment we are planning only to add the FlightInformationReq.

I believe we'll deliver the PR next monday (7th October).

**Comment by MiseCZ** [comment]
I believe everything's done here.

**Comment by dchertousov** [comment]
@shmuga , have you planed to fix some documentation?

**Comment by dchertousov** [comment]
@MiseCZ , I can see link to the FlightService at the bottom of README.md
Also @shmuga pointed some tiny issues and planned to fix them

**Comment by MiseCZ** [comment]
Ok. Sorry to be hasty. 

Pls @jirismika how's your plan to correct things?

**Comment by shmuga** [comment]
@MiseCZ I'll take that for me. It's mainly improvements or minor fixes than critical bugs.

**Comment by shmuga** [comment]
Everything fixed in https://github.com/Travelport-Ukraine/uapi-json/commit/ae40b18943643e9162868ad50ec8838b9b1cf7be
