### ISSUE TITLE
Output hotel country TRM code or location for each result

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#331]
For filtering hotel search results according to countries, as requested by our partner, I've added `HotelLocation` field for each result, which is either a TRM location code or IATA code (depends on search query).

Usually the `HotelProperty`.`Location` field turns up empty, and as a fallback the `code`/`location` from search query is simply copied into ouput. See [search example](https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Hotels/search.js) for reference

Since current search queries using HotelSearchAvailabilityReq only allow search for one city, such de-normalized format might seem not make sense; but it makes sense if users are aggregating results from several queries and/or are trying to filter them by country according to some business rules.

Support can be added into uapi-json later for 1G "Distance" from location or "Reference points" searches by coordinates
https://support.travelport.com/webhelp/uapi/uAPI.htm#Hotel/Hotel_Search/HotelSearchLocation/HotelLocation.htm%3FTocPath%3DHotel%7CHotel%2520Shopping%2520and%2520Booking%7CHotel%2520Search%7CHotel%2520Location%2520Search%2520Modifiers%7C_____1
It requires special provisioning for TargetBranch.

Moreover, search results by IATA code, might return several cities, with `HotelProperty`.`Location` field non-empty.

Note: country name in text is also returned as part of hotel information.

**Comment by shmuga** [comment]
Closing as merged
