### ISSUE TITLE
Improve parsing of errors for FOP type Card

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#332]
I've added improved exception handling for error 12008 (which is a host error during ticketing) for messages related to payment by credit card:

- AirRuntimeError.TicketingFOPUnavailable
> Host error during ticket issue. FOP SELECTED NOT AUTHORIZED FOR CARRIER XX

This error happens if an air company does not accept credit card payments in a particular country.

- AirRuntimeError.TicketingCreditCardRejected 
> Host error during ticket issue. REFUSE CREDIT

This error happens when credit card is bad or has insufficient funds.

**Comment by dchertousov** [comment]
Closed in corresponding PR in version 0.19.2
