### ISSUE TITLE
Attribute 'SolutionResult' is not allowed to appear in element 'air:AvailabilitySearchReq

### ISSUE THREAD

**Issue by engrashid** [Travelport-Ukraine/uapi-json#339]
with below request I am getting 
Attribute 'SolutionResult' is not allowed to appear in element 'air:AvailabilitySearchReq error
<soap:Envelope 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:AvailabilitySearchReq
            AuthorizedBy="user" TraceId="4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60" TargetBranch="P7002731"
            SolutionResult="true"
            ReturnBrandedFares="true"
            
      xmlns:air="http://www.travelport.com/schema/air_v36_0"
            
      xmlns:com="http://www.travelport.com/schema/common_v36_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="IEV" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="NYC" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2018-11-10"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
                IncludeFlightDetails="true"
            >
        <air:PreferredProviders>
          <com:Provider Code="1G" 
            xmlns:com="http://www.travelport.com/schema/common_v36_0"/>
          </air:PreferredProviders>
        </air:AirSearchModifiers>
        <com:SearchPassenger Code="ADT" 
          xmlns:com="http://www.travelport.com/schema/common_v36_0"/>
        </air:AvailabilitySearchReq>
      </soap:Body>
    </soap:Envelope>
 

SolutionResult="true" attributes causing this issue. But it automatically appending to request.
Please help how to remove that.

**Comment by shmuga** [comment]
@engrashid Sorry for a small delay with publishing. Now your fix is released under 0.20.4 version. Thanks for the contribution!
