### ISSUE TITLE
Enter queue request api

### ISSUE THREAD

**Issue by ranjithasiva** [Travelport-Ukraine/uapi-json#347]
Hi,
         I have successfully created till queuing api.In queuing api, there are two segments which is queue place request and entering queue request.In this npm,upto queue place request is available and after sending api from postman i am not getting any response .there is no module available for enetering queue place request

**Comment by dchertousov** [comment]
Hello @ranjithasiva 
Could you please give me an example of your request?

**Comment by ranjithasiva** [comment]
i have successfully PNR when i am calling Airservice.book method.After PNR is genrated in one pcc we are calling AirService.queue() api to queue the generated pnr to another PCC (our pcc) .In queueing api, i am not get any response in postman .It is taking so long time to load.
If the pnr generated is,BW1N1M in 57CH PCC,i will be queuing this PNR to another pcc as,follows,
{
	"queue": "80", // queue number
  "pcc": "74HR", // pcc
  "pnr": "BW1N1M" //pnr
}

in which i am not getting any response in postman.

**Comment by ranjithasiva** [comment]
@dchertousov  yes,the logs which i am printing is not showing in console..from Airservice.queue() , i am not response.

could you please explain,after pnr generated which api i should call?.whether in booking api is ticketing will be completed.

**Comment by dchertousov** [comment]
@ranjithasiva If you don't know what FQ is, you have to contact your local TVPT authorities :)
We are here to help you with the lib. Cheers!
