### ISSUE TITLE
Change Default Region

### ISSUE THREAD

**Issue by CharlesOwens5** [Travelport-Ukraine/uapi-json#348]
Is there any flags or configs to set the regions in the url for each request?

**Comment by dchertousov** [comment]
Hello @CharlesOwens5.
What do you mean by setting the region?

**Comment by CharlesOwens5** [comment]
Hey @dchertousov 
The request url is built with the following code:
const url = `https://${region}.universal-api.${prefix}travelport.com/B2BGateway/connect/uAPI`;
This is the url endpoint created:
https://emea.universal-api.travelport.com/B2BGateway/connect/uAPI/HotelService
Is there any options for me to change the region variable? 
The endpoint I am trying to hit is https://americas.universal-api.travelport.com/B2BGateway/connect/uAPI/HotelService

**Comment by dchertousov** [comment]
Documentation ticket is created. This ticket could be now closed.
