### ISSUE TITLE
Add auth.region param to the documentation

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#349]
Region could be passed as `auth.region`. This feature is not yet documented, but is used by library users, as you can see from #348.

Should be added in 1.0.2 as it is easy to do it.

**Comment by ranjithasiva** [comment]
hi dchertousov..npm uapi-json is very useful to do..thanks..when i am trying to call airservice.ticket() method it is calling universal record pnr api..but i want ticketing request api.could you please help me to do that???.

And also in queuing api method,api is calling queue place api..there is no entering queue request api..i need that also.

please check and le t me know to do

**Comment by dchertousov** [comment]
Hello @ranjithasiva.
Please create a separate issue for each of your question, so we should be able to focus on each of it.

**Comment by dchertousov** [comment]
Closed in #352
