### ISSUE TITLE
Canceling PNR without tickets

### ISSUE THREAD

**Issue by Dezaimasu** [Travelport-Ukraine/uapi-json#359]
When trying to call cancelPNR method for recently created PNR, without any issued tickets, error is returned.

It happens because cancelPNR tries to get tickets and check their status before canceling PNR, and getTickets methods throws exception if there's no tickets 
https://github.com/Travelport-Ukraine/uapi-json/blob/abfc3080c078e75c607956c7d05e1a022db7ded9/src/Services/Air/Air.js#L206

Argument "cancelTickets" for cancelPNR changes nothing. It tries to retrieve tickets either way.

Would it be possible to call for this:

https://github.com/Travelport-Ukraine/uapi-json/blob/abfc3080c078e75c607956c7d05e1a022db7ded9/src/Services/Air/Air.js#L329-L333

skipping this whole part that checks tickets' current state: 

https://github.com/Travelport-Ukraine/uapi-json/blob/abfc3080c078e75c607956c7d05e1a022db7ded9/src/Services/Air/Air.js#L286-L328

**Comment by dchertousov** [comment]
Hello @Dezaimasu !

It's so nice you dig so deep into the code!

You could open your own pull request and we will incorporate your changes, or we will try to fix this issue later next week.

**Comment by Dezaimasu** [comment]
I think there's a bug in the code, when you're calling getUniversalRecordByPNR inside cancelPNR, it returns not a record, but an array of records, so "record.uapi_reservation_locator" wouldn't find anything. 

https://github.com/Travelport-Ukraine/uapi-json/blob/abfc3080c078e75c607956c7d05e1a022db7ded9/src/Services/Air/Air.js#L286-L288

Tried to fix that, but now tests are failing. I'll add it to pull request anyway because I'm quite sure it was an actual bug and tests should be adjusted as well. Just reject it if I'm wrong.

**Comment by dchertousov** [comment]
@Dezaimasu , good!
Could you write test for it and create a PR?

**Comment by dchertousov** [comment]
Closed in #360
