### ISSUE TITLE
NO PLATING CARRIER FOUND

### ISSUE THREAD

**Issue by engrashid** [Travelport-Ukraine/uapi-json#364]
I am having following issue with AirPriceReq . If I add 

this segment  <air:AirPricingModifiers PlatingCarrier="{{platingCarrier}}"/> in AIR_PRICE_REQ.handlebars.js it resolves the issue 

`Request URL:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService
Request XML:

<soap:Envelope
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <air:AirPriceReq
            AuthorizedBy="user" CheckFlightDetails="true" TargetBranch="P7111966"
            TraceId=""

      xmlns:air="http://www.travelport.com/schema/air_v36_0"

      xmlns:com="http://www.travelport.com/schema/common_v36_0">
      <com:BillingPointOfSaleInfo OriginApplication="UAPI"
        xmlns:com="http://www.travelport.com/schema/common_v36_0"/>
        <air:AirItinerary>
          <air:AirSegment ArrivalTime="2019-01-01T17:20:00.000+05:30"
                                DepartureTime="2019-01-01T14:55:00.000+06:00"
                                Carrier="9W"
                                 ClassOfService="L"
                                CabinClass="Economy"
                                Origin="DAC"
                                Destination="DEL"
                                ETicketability="Yes"
                                Equipment="738"
                                FlightNumber="279"
                                LinkAvailability="true"
                                PolledAvailabilityOption="Polled avail exists"
                                ProviderCode="1G"
                                Key="0"
                                Group="0">
            <air:Connection/>
          </air:AirSegment>
          <air:AirSegment ArrivalTime="2019-01-02T17:40:00.000+00:00"
                                DepartureTime="2019-01-02T13:25:00.000+05:30"
                                Carrier="9W"
                                 ClassOfService="L"
                                CabinClass="Economy"
                                Origin="DEL"
                                Destination="LHR"
                                ETicketability="Yes"
                                Equipment="77W"
                                FlightNumber="122"
                                LinkAvailability="true"
                                PolledAvailabilityOption="Polled avail exists"
                                ProviderCode="1G"
                                Key="1"
                                Group="0"></air:AirSegment>
          <air:AirSegment ArrivalTime="2019-01-09T16:10:00.000+06:00"
                                DepartureTime="2019-01-09T13:25:00.000+05:30"
                                Carrier="9W"
                                 ClassOfService="K"
                                CabinClass="Economy"
                                Origin="DEL"
                                Destination="DAC"
                                ETicketability="Yes"
                                Equipment="739"
                                FlightNumber="272"
                                LinkAvailability="true"
                                PolledAvailabilityOption="Polled avail exists"
                                ProviderCode="1G"
                                Key="2"
                                Group="1">
            <air:Connection/>
          </air:AirSegment>
          <air:AirSegment ArrivalTime="2019-01-09T10:55:00.000+05:30"
                                DepartureTime="2019-01-08T20:40:00.000+00:00"
                                Carrier="9W"
                                 ClassOfService="K"
                                CabinClass="Economy"
                                Origin="LHR"
                                Destination="DEL"
                                ETicketability="Yes"
                                Equipment="77W"
                                FlightNumber="121"
                                LinkAvailability="true"
                                PolledAvailabilityOption="Polled avail exists"
                                ProviderCode="1G"
                                Key="3"
                                Group="1"></air:AirSegment>
        </air:AirItinerary>
        <air:AirPricingModifiers InventoryRequestType="DirectAccess"/>
        <com:SearchPassenger Key="P_0" Code="ADT" Age="18"
          xmlns:com="http://www.travelport.com/schema/common_v36_0"/>
          <air:AirPricingCommand>
            <air:AirSegmentPricingModifiers AirSegmentRef="0" FareBasisCode="L2HRTBD"/>
            <air:AirSegmentPricingModifiers AirSegmentRef="1" FareBasisCode="L2HRTBD"/>
            <air:AirSegmentPricingModifiers AirSegmentRef="2" FareBasisCode="K2HE3MBD"/>
            <air:AirSegmentPricingModifiers AirSegmentRef="3" FareBasisCode="K2HE3MBD"/>
          </air:AirPricingCommand>
        </air:AirPriceReq>
      </soap:Body>
    </soap:Envelope>

Response SOAP:  <SOAP:Envelope
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>000292 NO PLATING CARRIER FOUND </faultstring>
      <detail>
        <common_v36_0:ErrorInfo
          xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0">
          <common_v36_0:Code>3318</common_v36_0:Code>
          <common_v36_0:Service>AIRSVC</common_v36_0:Service>
          <common_v36_0:Type>Business</common_v36_0:Type>
          <common_v36_0:Description>No Plating Carrier Found.</common_v36_0:Description>
          <common_v36_0:TransactionId>0886E82C0A076478180B87E7FFE5AC76</common_v36_0:TransactionId>
          <common_v36_0:TraceId/>
        </common_v36_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>`

**Comment by Smotrov** [comment]
Dear @engrashid! 
Thank you for your findings! 
You could open your own pull request and we will incorporate your changes.

**Comment by engrashid** [comment]
> Dear @engrashid!
> Thank you for your findings!
> You could open your own pull request and we will incorporate your changes.

Sure will do

**Comment by dchertousov** [comment]
@paulvoloschuk 
Please extend `book` and `fareRules` methods with optional `platingCarrier` param.
- [ ] Add optional parameter to the XML
- [ ] Add passing param to the XML from `book` and `fareRules` method
- [ ] Add examples
- [ ] Add docs
- [ ] Add tests (Test should check if XML template respects `platingCarrier` param)
