### ISSUE TITLE
Travelport schema version outdated  

### ISSUE THREAD

**Issue by engrashid** [Travelport-Ukraine/uapi-json#365]
HI 
according to this link https://support.travelport.com/webhelp/uapi/uAPI.htm#SchemaRetirement.htm%3FTocPath%3D_____19
After December 15, 2018, the following schema versions from Release 15.2 and Release 15.3 will not be supported.
So schema version used in this module going to be discontinued. So I am slightly confused if its still usable until we migrate to new schema version . 

Can I get some thoughts on this ? 

thanks

**Comment by raymond180** [comment]
I just tried the air service and this is what I got "Invalid version specified/configured air_v33_0." The air service is indeed outdated.

**Comment by dchertousov** [comment]
We are going to put this into the nearest version update, but your PRs are most certainly welcome :)

**Comment by dchertousov** [comment]
@paulvoloschuk  please study difference between latest and current version and create a report here

**Comment by paulvoloschuk** [comment]
I investigated differences in schema versions and made archive with screenshots.
[Uploading Hotels:Air.diff.zip…](Air.diff.zip)

**Comment by dchertousov** [comment]
@InkFaust see diff here: https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Universal_API_Schemas_and_WSDLs.htm%3FTocPath%3D_____18

**Comment by dchertousov** [comment]
Another useful link: https://support.travelport.com/webhelp/uapi/uAPI.htm#SchemaRetirement.htm

**Comment by dchertousov** [comment]
Schema updates to cover:

- [ ] Air
- [ ] Utils
- [ ] Common
- [ ] GdsQueue
- [ ] Hotels
