### ISSUE TITLE
Airfare Rule Error 

### ISSUE THREAD

**Issue by lifeofdubem** [Travelport-Ukraine/uapi-json#371]
# Request

`const requestPTC = 'ADT';

    const shop_params = {
      legs: [
        {
          from: 'LWO',
          to: 'CGK',
          departureDate: '2019-03-20',
        },
        {
          from: 'CGK',
          to: 'KBP',
          departureDate: '2019-04-21',
        },
      ],
      passengers: {
        [requestPTC]: 1,
      },
      cabins: ['Economy'],
      requestId: 'test',
    };

    return this.uapi.shop(shop_params)
      .then((results) => {
        const forwardSegments = results['0'].directions['0']['0'].segments;
        const backSegments = results['0'].directions['1']['0'].segments;

        const farerules_params = {
          segments: forwardSegments.concat(backSegments),
          passengers: shop_params.passengers,
          long: true,
          requestId: 'test',
        };

        return this.uapi.fareRules(farerules_params);
      })
      .then(
        (res) => res,
        err => err
      ).catch((err) => err);`

# Response

`{
    "name": "RequestRuntimeError.UnhandledError",
    "data": null,
    "causedBy": {
        "name": "RuntimeError.AirRuntimeError",
        "data": {
            "faultcode": "Server.InvalidRequestException",
            "faultstring": "[Error] :5:368: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '2' for type 'typeProviderCode'.",
            "detail": {
                "ErrorInfo": {
                    "Code": "1000",
                    "Service": "WEBSVC",
                    "Type": "Data",
                    "Description": "Validation failed on request message.",
                    "TransactionId": "0A9917120A0764774089D11797837BC2",
                    "Auxdata": {
                        "Entry": {
                            "Reason": "\nLastElement",
                            "Description": "AirItinerary ArrivalTime=2019-03-20T13:10:00.000+02:00 DepartureTime=2019-03-20T10:05:00.000+02:00 Carrier=TK ClassOfService=P CabinClass=Economy Origin=LWO Destination=IST ETicketability=Yes Equipment=73H FlightNumber=442 LinkAvailability=true PolledAvailabilityOption=Polled avail exists ProviderCode= Key=0 Group=0"
                        }
                    },
                    "xmlns": "http://www.travelport.com/schema/air_v36_0"
                }
            }
        }
    }
}`

**Comment by lifeofdubem** [comment]
Can anyone help me out with this issue, please

**Comment by Smotrov** [comment]
Dear @lifeofdubem is [this example](https://github.com/Travelport-Ukraine/uapi-json/blob/master/examples/Air/shop.js) works well for you?

**Comment by lifeofdubem** [comment]
Hello @Smotrov  the problem is not with the funtion `this.uapi.shop()`, but with the this `this.uapi.fareRules(farerules_params)`.

**Comment by lifeofdubem** [comment]
The problem is caused by the [AIR_PRICE_REQ.handlebars.js](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Services/Air/templates/AIR_PRICE_REQ.handlebars.js)                                 ProviderCode="{{provider}}" as provider is not return as part of the segment.

**Comment by Smotrov** [comment]
Cool! Can I ask you to do a Pull request?

**Comment by lifeofdubem** [comment]
@Smotrov I have already create a Pull request

**Comment by lifeofdubem** [comment]
@Smotrov @cursedcoder @jirismika @Axxoul  check out  this new wrapper I start off with few days ago. It has extremely more advanced search functionality. Your contributions will be highly appreciated.
