### ISSUE TITLE
Missing HostToken

### ISSUE THREAD

**Issue by yaerhf** [Travelport-Ukraine/uapi-json#388]
Hi,

I get this error when trying to book:
 'The following attribute is missing in the AirCreateReservationReq: AirPricingSolution/HostToken'

When I search the xmls for air:airPricingSolution it has an attribute named 'Key' but not 'HostToken'.

Could you help me?

**Comment by dchertousov** [comment]
Hello!
We have recently updated the schema, so it may have some sharp angles.
You may contribute into this lib, if you have a fix for that already.

**Comment by yaerhf** [comment]
Hi,
It was difficult to understand how it works but I successfully patched this by modifying AirParser.js and AIR_CREATE_RESERVATION_REQUEST.handlebars.js 

I've committed in my fork.

**Comment by dchertousov** [comment]
Could you please follow [this instruction](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) to contribute into the library? We will be happy to release your patch!

**Comment by dchertousov** [comment]
Fixed in #390
