### ISSUE TITLE
Add support to log raw XML request/response to file 

### ISSUE THREAD

**Issue by engrashid** [Travelport-Ukraine/uapi-json#391]
with a new debug level introduced adding support to write raw XML request/response would be very much helpful 

Proposed solution 
debug level 4 
xml log will be written in file

**Comment by engrashid** [comment]
@dchertousov  Can you comment on above feature ? I would like to to contribute on this feature .

**Comment by dchertousov** [comment]
As XML requests/responses are already included into output with another debug level, I don't see a reason to have logging in files, as such files should be managed then, otherwise we could overflow user's disk with messages.

**Comment by engrashid** [comment]
Hmm may be you are right.
But i see a personal need as we have to examine  each request and response .
Output in console ate up lot if space as xmls are very big .Hence putting in files help to look at xml and debug request.

**Comment by dchertousov** [comment]
What do you think about the event model for the service, where you can subscribe on ‘onRequest’ and ‘onResponse’ event and log into files on your own?

**Comment by engrashid** [comment]
That would be great

**Comment by dchertousov** [comment]
@cursedcoder what’s your opinion on that?

**Comment by Chitzi** [comment]
I was just looking for this feature. Any news?

**Comment by jthoma** [comment]
Even I was also looking for this, as I am running the wrapper in AWS Lambda large xml would overflow the console.log buffer and get cut off. Getting the xml and sending that to api support would be tough to identify where it went wrong. 

Suggesting that if debug is a writable file stream, do the logging there. Well about managing the filesystem, it should be the responsibility of the user.

**Comment by shmuga** [comment]
@jthoma @Chitzi @engrashid Have you considered passing logFunction as on of the options as described [here](https://github.com/Travelport-Ukraine/uapi-json#options)? It will [replace default console.log](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Request/uapi-request.js#L45) with a function of your choice. So you could store and publish logs where it's more suitable for you.

**Comment by cursedcoder** [comment]
I think what @shmuga suggests should be sufficient.
We use this for a long time on our side and put XMLs into a separate cloudwatch group.

**Comment by jthoma** [comment]
@shmuga  took your suggestion and posted something ;) 
@engrashid , @Chitzi  if any one of you are running it on AWS then just check this [here](https://github.com/jthoma/code-collection#awscloud-watch-uapi-xml-logger)
