### ISSUE TITLE
Max of 80 results from LFS via uapi-json even though there are more

### ISSUE THREAD

**Issue by wesnolte** [Travelport-Ukraine/uapi-json#395]
Hi there, 

I'm getting a max of 80 results via LFS using uapi-json, however if I use another client I can get more results. Where is this limit being imposed?

Wes

**Comment by creduo** [comment]
You can add maxSolutions to the request XML

**Comment by dchertousov** [comment]
Hello everyone!

@wesnolte  Do you suggest to add a new param in LFS?
@creduo Could you please PR on this matter?

**Comment by wesnolte** [comment]
Hi there, I've modified the code so that I can pass a Max Solution attribute but this is not what I'm asking about. My question is, I only ever receive a maximum of 80 results even if I set MaxSolutions=200. Therefore I'm guessing this is a limit of uAPI? Please confirm.

Thanks,

Wes Nolte
Chief Technology Officer | SalesTrip
07812374272

**Comment by Smotrov** [comment]
Hi @wesnolte  
This setting is stored in you's PCC configuration. Please refer to your local Travelport representative office to change it. There are 3 _tiers_ of this.
