### ISSUE TITLE
Support for solutionResults in Low Fare Search Request

### ISSUE THREAD

**Issue by creduo** [Travelport-Ukraine/uapi-json#403]
uAPI LFS returns two kinds of results, AirPricePointList and AirPricingSolution but formatLowFaresSearch only parses AirPricePointList.

It'd be good to have AirPricingSolution support (SolutionResults) too.

**Comment by Smotrov** [comment]
Hi @creduo! 
Yes, you are right. 
Unfortunately, Shopping functions are not in our current priority.
However but though, we would just love to accept your contribution if you feel you can cope with that.
