### ISSUE TITLE
When i run availability API then i a get

### ISSUE THREAD

**Issue by scokbulbul** [Travelport-Ukraine/uapi-json#410]
Input params  {
  "legs": [
    {
      "from": "BOM",
      "to": "DEL",
      "departureDate": "2019-05-25"
    }
  ],
  "passengers": {
    "ADT": 1
  },
  "carriers": [
    "KL"
  ],
  "cabins": [
    "Economy"
  ],
  "requestId": "4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60"
}
Request URL:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/kestrel/AirService
Request XML:  
<soap:Envelope 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:AvailabilitySearchReq
            AuthorizedBy="user" TraceId="4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60" TargetBranch="P7039070"
            
      xmlns:air="http://www.travelport.com/schema/air_v47_0"
            
      xmlns:com="http://www.travelport.com/schema/common_v47_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="BOM" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="DEL" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2019-05-25"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
                IncludeFlightDetails="true"
            >
        <air:PreferredProviders>
          <com:Provider Code="1G" 
            xmlns:com="http://www.travelport.com/schema/common_v47_0"/>
          </air:PreferredProviders>
          <air:PermittedCarriers>
            <com:Carrier Code="KL" 
              xmlns:com="http://www.travelport.com/schema/common_v47_0"/>
            </air:PermittedCarriers>
          </air:AirSearchModifiers>
          <com:SearchPassenger Code="ADT" 
            xmlns:com="http://www.travelport.com/schema/common_v47_0"/>
          </air:AvailabilitySearchReq>
        </soap:Body>
      </soap:Envelope>

Response SOAP:  <SOAP:Envelope 
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.System</faultcode>
      <faultstring>No more later flights.</faultstring>
      <detail>
        <common_v47_0:ErrorInfo 
          xmlns:common_v47_0="http://www.travelport.com/schema/common_v47_0">
          <common_v47_0:Code>20</common_v47_0:Code>
          <common_v47_0:Service>AIRSEARCH_SERVICE</common_v47_0:Service>
          <common_v47_0:Type>System</common_v47_0:Type>
          <common_v47_0:Description>No more later flights.</common_v47_0:Description>
          <common_v47_0:TransactionId>D545BA2D0A07643CCFC86C0192A8CD69</common_v47_0:TransactionId>
          <common_v47_0:TraceId>4e2fd1f8-2221-4b6c-bb6e-cf05c367cf60</common_v47_0:TraceId>
        </common_v47_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
{ RequestRuntimeError.UnhandledError: Error during request. Please try again later
    at Parser.AirErrorHandler (/home/pradeep/Desktop/Bulbul/Travel Port/NodeJS/uapi-json-master/src/Services/Air/AirParser.js:318:13)
    at validateSOAP (/home/pradeep/Desktop/Bulbul/Travel Port/NodeJS/uapi-json-master/src/Request/uapi-request.js:147:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'RequestRuntimeError.UnhandledError',
  data: null,
  causedBy:
   { RuntimeError.AirRuntimeError: Air service runtime error
       at Parser.AirErrorHandler (/home/pradeep/Desktop/Bulbul/Travel Port/NodeJS/uapi-json-master/src/Services/Air/AirParser.js:318:58)
       at validateSOAP (/home/pradeep/Desktop/Bulbul/Travel Port/NodeJS/uapi-json-master/src/Request/uapi-request.js:147:29)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'RuntimeError.AirRuntimeError',
     data:
      { faultcode: 'Server.System',
        faultstring: 'No more later flights.',
        detail: [Object] } } }

please advice.
thanks in advance

**Comment by Smotrov** [comment]
Are you sure that KLM operates BOM-DEL?

**Comment by creduo** [comment]
KL is no longer available since their platingCarrier for BOM-DEL, 9W ceased operation.
