### ISSUE TITLE
Fix vulnerabilities in uapi-json dependencies

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#417]
uapi-json now has vulnerabilities in the package dependencies, so we might consider resolving them before reeleasing new version of uapi-json

**Comment by shmuga** [comment]
Fixed in #415

**Comment by dchertousov** [comment]
Not fixed, as we still receive a message about outdated lodash

**Comment by shmuga** [comment]
Weird. I've tried to run `npm audit` and received only this message.
```
❯ npm --version                                                                                                                                            
6.10.1

❯ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 999 scanned packages
```

Could you help me with listing vulnerabilities?

**Comment by dchertousov** [comment]
Got the same audit result. Maybe the GitHub message is now outdated

**Comment by dchertousov** [comment]
https://github.com/Travelport-Ukraine/uapi-json/network/alert/package-lock.json/lodash/open

**Comment by dchertousov** [comment]
And yes we have older lodash version in package-lock.json
Audit does not show any issues, though github shows

**Comment by shmuga** [comment]
@dchertousov Getting 404 [here](https://github.com/Travelport-Ukraine/uapi-json/network/alert/package-lock.json/lodash/open)? Does it for you?

**Comment by dchertousov** [comment]
<img width="776" alt="Screenshot 2019-07-13 at 14 42 09" src="https://user-images.githubusercontent.com/2781628/61171770-750fac80-a57c-11e9-8b8d-f9f440cbd367.png">
