### ISSUE TITLE
Cabin Class Limitation

### ISSUE THREAD

**Issue by Yeab13** [Travelport-Ukraine/uapi-json#435]
At the moment, Travelport supports more than 2 cabin classes on LowFareSearch, but on uapi-json only "Economic" & "Business" are available. 
The cabin class below are available :
1.Premium First
2.First
3.Business
4. Upper - applies to PreferredCabin only (available with Air v35.0) Release 15.5
5. Premium Economy
6. Economy (Coach)

Source : https://github.com/Travelport/travelport-uapi-tutorial/issues/201

**Comment by creduo** [comment]
uapi-json is just a wrapper, it will pass the cabin as requested in PreferredCabin. Even cabins is plural and is in array, only one value will be accepted. 

Available values are "Economy", "PremiumEconomy", "Upper", "Business", "First", "PremiumFirst".

**Comment by Yeab13** [comment]
Excellent, Thank You very much
