### ISSUE TITLE
Segments formatted wrongly

### ISSUE THREAD

**Issue by InkFaust** [Travelport-Ukraine/uapi-json#438]
During booking segments retrieving, the segments are formatted wrongly.
https://github.com/Travelport-Ukraine/uapi-json/blob/abfc3080c078e75c607956c7d05e1a022db7ded9/src/Services/Air/AirFormat.js#L238
Here `ProviderSegmentOrder` should be used instead of `TravelOrder `.
Please cover with tests.

**Comment by cursedcoder** [comment]
That's a breaking change and version should be bumped towards minor point.
