### ISSUE TITLE
AirCreateReservation

### ISSUE THREAD

**Issue by Yeab13** [Travelport-Ukraine/uapi-json#441]
Hello,

I have got SRR

`<com:SSR` Type="{{type}}" FreeText="{{text}}"/>
               

                         <!--SegmentRef="IVaa0tGWQ+2grqSIL81xPQ==" Status="HK" `Type="DOCS"/>-->`

I have got this from AIR_CREATE_RESERVATION_REQUEST.handlebars.js  

As you can see from the above set of code, the first line is what is being used which sets SSR type and free text only. The second code is what I need which sets Carrier, FreeText, SegmentRef, Status ... 

The second code is just static / hardcoded value. Is it possible to fill those values dynamically as per the booking request? The second code is the correct version ( which is expected from Travelport end), but it is not dynamic/complete.   If it is not dynamically populated, there is a warning which is returned from API.

Thank You

**Comment by creduo** [comment]
You can change the line as  
`<com:SSR Type="{{type}}" {{#if carrier}}Carrier="{{carrier}}" {{/if}}{{#if status}} status="{{status}}" {{/if}}{{#if segmentRef}}SegmentRef="{{segmentRef}}" {{/if}}FreeText="{{text}}" />` 

then, 
`
            "ssr": {
            	"type": "FQTV",
            	"carrier": "XB",
            	"text": "XB12345678"
            }
`
in passenger of the create booking request.

The PR I opened was from a few months back, so it looks like need some changes to tests.
But the single line change above might be sufficient for what you need during AirCreateBooking request (note this is not for URModify/Air)

**Comment by Yeab13** [comment]
`<common_v47_0:SellMessage>ADD ADVANCE PASSENGER INFORMATION SSRS DOCA/DOCO/DOCS</common_v47_0:SellMessage>`

Thank You, I have used the above code and it works very well but I got the above warning. Is it okay?     

Also, I have got this on the JSON returned from the Reservation response.
`"messages": [
      {
        "_": "NO FARES",
        "Code": "0",
        "Type": "Warning",
        "ProviderCode": "1G"
      },
      {
        "_": "Some of the requested AirPricingInfos could not be saved for the requested provider.",
        "Code": "0",
        "Type": "Warning",
        "ProviderCode": "1G"
      },
      {
        "_": "The following attribute is missing in the AirCreateReservationReq: AirPricingSolution/HostToken.",
        "Code": "0",
        "Type": "Error",
        "ProviderCode": "1G"
      }
    ]`

As you can see from the above code , there is this warning -  "The following attribute is missing in the AirCreateReservationReq: AirPricingSolution/HostToken". Is there any way to solve this? 

Thank You

**Comment by creduo** [comment]
PNR will be created without providing them, but in real life, DOC*, CTC* SSRs are not optional.
you can pass them in array, handlebar will handle them

`
"ssr":[{ "type": "DOCS", "text": "...." }, { "type": "CTCE", "carrier": "XB", "text": "test//example.com" }]
`

For host token, you should add HostToken which comes with LFS or AirPrice result to the air create booking request.

**Comment by Yeab13** [comment]
`const book = {
        segments: fromSegments,
        rule: 'SIP',
        passengers: [
          {
            lastName: 'JOHN',
            firstName: 'DOE',
            passCountry: 'ET',
            passNumber: 'ET7823J',
            birthDate: '1997-02-18',
            gender: 'M',
            ageCategory: 'ADT',
          }
        ],
        phone: {
          countryCode: '38',
          location: 'IEV',
          number: '033440419905',
        },
        allowWaitlist: true,
        ssr:[
          { "type": "DOCS", "carrier": "ET", "text": "test//example.com" }],
      };`

Is this correct ? I think it is expected to send SSR like this after this json is parsed to XML 
`<com:SSR Type="DOCS" Status="HK" Carrier="YY" FreeText="P/US/1234567/US/25Jan85/M/23OCT17/Lastname/Firstname"/>`

I tried to send the above JSON and I didn't get any new changes ... Still there is such warning `<common_v47_0:SellMessage>ADD ADVANCE PASSENGER INFORMATION SSRS DOCA/DOCO/DOCS</common_v47_0:SellMessage>`
