### ISSUE TITLE
Multi-City Flight Option ?

### ISSUE THREAD

**Issue by Yeab13** [Travelport-Ukraine/uapi-json#449]
Do uapi-json support a multi-city flight option? 

> For instance: A passenger may want to fly from place A to B on a specific date, and then fly from B to C on another specific date.  

Is it possible to book such a multi-city flight via uapi-json ? Or I have to search multiple times? ( like from A-to-B become 1 flight segment, B-to-C become 1 flight segment ... this will continue and the total segment will be given as input for book.js )

Thank You

**Comment by creduo** [comment]
Please read this

https://github.com/Travelport-Ukraine/uapi-json/blob/master/docs/Air.md#leg

You should shop with legs, and book with segments from shop result
