### ISSUE TITLE
Terminal commands in  AirService.ticket

### ISSUE THREAD

**Issue by kshitij1414** [Travelport-Ukraine/uapi-json#454]
Can somebody please explain how does the AirService.ticket function work ? I need to add some cryptic commands in the same session when the ticket is being issued, is it possible in uapi?

**Comment by Smotrov** [comment]
Dear @kshitij1414  please find [documentation](https://github.com/Travelport-Ukraine/uapi-json/tree/master/examples/Terminal) and [examples](https://github.com/Travelport-Ukraine/uapi-json/tree/master/examples/Terminal) of cryptic entries. 

Hope it helps.

**Comment by kshitij1414** [comment]
Dear @Smotrov 
How do I implement them in AirService.ticket
Problem Statement :- I need to execute a terminal command just before the ticketing command(TKP)or any other command is executed ie in the same session..
Thanks for your help..
