### ISSUE TITLE
search with both arrival and departure dates.

### ISSUE THREAD

**Issue by digital230** [Travelport-Ukraine/uapi-json#457]
Hi, 
can we search with both arrival and departure dates. right now LowFareSearchReq is not accepting both giving errors. is there any way to find flights between departure and arrival date

**Comment by jthoma** [comment]
Hi
As per the [Travelport Documentation](https://support.travelport.com/webhelp/uapi/Subsystems/Schemas/Content/Schemas/LowFareSearchReq.html) SearchArvTime is not supported by LowFareSearchReq. Similarly the uapi-json also does not support the same.

**Comment by digital230** [comment]
Hi, 
thanks for answer .. is there anyway we can search with both. or any formula, trick?

**Comment by creduo** [comment]
You should first search using SearchDepTime and filter out.

**Comment by digital230** [comment]
Thanks.
