### ISSUE TITLE
Flight Terminal info missing from Shop Response

### ISSUE THREAD

**Issue by jthoma** [Travelport-Ukraine/uapi-json#474]
Air.shop response misses the terminal information. 

Resolve the same by adding the corresponding response params from flightDetails alias flightInfo in /src/Services/Air/AirFormat.js line 121 fn:formatTrip. 

Confusion for me due to my understating, why the flightInfo.map / flightInfo.slice(1).map all used. hence not making any commits there. But this is an absolute need for my production move which is scheduled by the end of this month.

**Comment by creduo** [comment]
#467 already implemented flight details in segments. seems like it wasn't merged back then?
