### ISSUE TITLE
Error while trying to shop by Economy and Business

### ISSUE THREAD

**Issue by sierovevhenii** [Travelport-Ukraine/uapi-json#481]
Hello, 

I tried to create Shop request in both (cabins: ['Economy', 'Business']) cabins. I get an error: "Error unmarshalling message body: Expected "{http://www.travelport.com/schema/air_v47_0}PreferredCabins" end tag, found "{http://www.travelport.com/schema/common_v47_0}CabinClass" start tag (line 21, col 58, in UTF-8)"

Could you please help me with this problem?

Best Regards,
Yevhenii Sierov.

**Comment by Yeab13** [comment]
![image](https://user-images.githubusercontent.com/26460205/85847081-86fb5700-b7af-11ea-9e27-f0509b32b7fc.png)

Hello Yevhenii Sierov,
    
I don't think it is possible to query multiple cabin classes even though uapi-json _cabins_ property accepts an array of cabin classes. As you can see from the image, it is only possible to query 1 cabin class only at a time. There are 2 options : **PreferredCabins** & **PermittedCabins**. PerferredCabins return an alternate cabin incase the cabin class you requested is not found / available , but PermittedCabins won't give you that flexibility.

For more information, checkout [this](https://support.travelport.com/webhelp/uapi/Content/Air/Low_Fare_Shopping/Low_Fare_Shopping_by_Cabin_Class.htm)

Thank You,
Yeabsira Gashaw

**Comment by Smotrov** [comment]
Dear @sierovevhenii do you have any other questions in this regards?

**Comment by sierovevhenii** [comment]
Hello team,

Thank you for response. I found such functionality in uapi-json and thought there was a way to do this.

Thank you,
Yevhenii Sierov.
