### ISSUE TITLE
when i try to pricing multiple legs, pricing will not work. 

### ISSUE THREAD

**Issue by kim00425** [Travelport-Ukraine/uapi-json#528]
when I try to shopping in legs A-B, B-C, and C-A, I receive data for a price of $2,000. however, then when I try to price with this data, I get a more discounted rate. i think, legs A-B, B-C, C-A are considered round-trip sections of A-C and seem to give me a cheaper fare. how do I get the same price I received when shopping at the time of pricing?

**Comment by Smotrov** [comment]
Hi! Most probably married logic apples on the core. Please contact your local travelport representative help desk for more details.
