### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by MohammaedAlani** [Travelport-Ukraine/uapi-json#530]
When i try login with URL it is login normally. but with SDK returun this

SoapRequestError [RequestSoapError.SoapRequestError]: Error during request to SOAP API. Check url validity
    at /Users/mohammedalani/Desktop/di/node_modules/uapi-json/src/Request/uapi-request.js:123:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  source: 'uapi-json',
  data: {
    status: 401,
    data: '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:faultcode>76</SOAP-ENV:faultcode><SOAP-ENV:faultstring>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:faultstring><SOAP-ENV:faultactor>            </SOAP-ENV:faultactor><SOAP-ENV:detail>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>'
  },
  statusCode: undefined
}

**Comment by Smotrov** [comment]
Hi @MohammaedAlani! 
It seems like your Authentication credentials are invalid. Please contact your local Travelport representative for check.
