### ISSUE TITLE
What does Air/FareRule Response  this Penalties Content mean?

### ISSUE THREAD

**Issue by koyoshiro** [Travelport-Ukraine/uapi-json#559]
When I Call Air/FareRule , it response content like :

```
{
"Name": "Penalties",
"Value": "CHG-75USD/CHG-100USD/CXL-NONREF/CXL-NONREF CHG FREE-0USD"
},
```

What does  `"Value": "CHG-75USD/CHG-100USD/CXL-NONREF/CXL-NONREF CHG FREE-0USD" ` mean?

**Comment by dchertousov** [comment]
Hello @koyoshiro !

I believe it will be best for you to contact your local Travelport support on explaining this values.

This library is just a wrapper for a standard Travelport uAPI protocol and despite changing response structure somehow it has nothing to do with the values in it.
