### ISSUE TITLE
Air Shop Error

### ISSUE THREAD

**Issue by MohammaedAlani** [Travelport-Ukraine/uapi-json#615]
When I try to search using shop() getting an error, but when using availability() it is working fine. I will share with you the full request and response from the log.

Input: 

`{
  "legs": [
    {
      "from": "DXB",
      "to": "BGW",
      "departureDate": "2023-02-18"
    }
  ],
  "passengers": {
    "ADT": 1
  },
  "cabins": [
    "Economy"
  ],
  "requestId": "4e2sa1f8-5431-4b6c-bb6e-cf05c367as43",
  "maxSolutions": 250,
  "pricing": {
    "currency": "USD"
  }
}`

Request URL:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService

Request:

`<soap:Envelope
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:LowFareSearchReq
            AuthorizedBy="user" TraceId="4e2sa1f8-5431-4b6c-bb6e-cf05c367as43" TargetBranch="P7002726"
            ReturnUpsellFare="true"
      xmlns:air="http://www.travelport.com/schema/air_v52_0"
      xmlns:com="http://www.travelport.com/schema/common_v52_0">
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="DXB" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="BGW" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2023-02-18"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers MaxSolutions="250">
        <air:PreferredProviders>
          <com:Provider Code="1G"
            xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
          </air:PreferredProviders>
        </air:AirSearchModifiers>
        <com:SearchPassenger Code="ADT"
          xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
          <air:AirPricingModifiers
                CurrencyType="USD"/>
        </air:LowFareSearchReq>
      </soap:Body>
    </soap:Envelope>`

Response:

`<SOAP:Envelope
  xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>UNABLE TO FARE QUOTE</faultstring>
      <detail>
        <common_v52_0:ErrorInfo
          xmlns:common_v52_0="http://www.travelport.com/schema/common_v52_0">
          <common_v52_0:Code>3037</common_v52_0:Code>
          <common_v52_0:Service>AIRSVC</common_v52_0:Service>
          <common_v52_0:Type>Business</common_v52_0:Type>
          <common_v52_0:Description>No availability on chosen flights.</common_v52_0:Description>
          <common_v52_0:TransactionId>A797C1BA0A0D6A93491055506FC1E29A</common_v52_0:TransactionId>
          <common_v52_0:TraceId>4e2sa1f8-5431-4b6c-bb6e-cf05c367as43</common_v52_0:TraceId>
        </common_v52_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>`

**Comment by kommandant-topp** [comment]
Hello @MohammaedAlani, I've checked from my side and the result is ok: no errors and a list of the flight details. The only difference is the target branch. Could it be your access creds? 

Thank you, and have a nice day!

**Comment by MohammaedAlani** [comment]
Hello @kommandant-topp,

But in the same target branch for another function (availability) get results for the same info. like from, to , date and the target branch.

Thank You for your fast response.

**Comment by kommandant-topp** [comment]
Hello @MohammaedAlani, I can create a ticket for your problem at the Travelport support desk. I need your username and PCC to create a ticket (and I assume that your targetBranch is P7002726)  

Thank you, and have a nice day!

**Comment by MohammaedAlani** [comment]
Hello @kommandant-topp,

Thank you for your support.

Username is => Universal API/uAPI1189214086-2752a905
TargetBranch => P7002726
Region => emea

For The PCC it is just a credential for testing and will be expired within 30 Days.

**Comment by MohammaedAlani** [comment]
Hello @kommandant-topp,

I will close this ticket but for more information to happy data test must use this link below for all regions.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Testing_Best_Practices/Testing_Best_Practices.htm

Thank you for your support.
