### ISSUE TITLE
Custom log function instead of default.

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#62]
Add possibility to override default log function to some custom.
Add definition for this function and replace or occurrences of console.log

**Comment by dchertousov** [comment]
Do you want to make it a paramour constructor?
How do you expect the override to work?

**Comment by shmuga** [comment]
There should be function like `function log(message, data)`, that can be passed as parameter in `settings` object. The default value for this function will be `(message, data) => console.log(message,data)`.
So it can be used to push log messages in some specific place (db,file etc.)

**Comment by shmuga** [comment]
Another way we can do it - we can export additional function `setLogFunction()` as external function and set it for whole application.

**Comment by dchertousov** [comment]
And what are you going to use by default if function was not provided? `console.log` or something else?

**Comment by shmuga** [comment]
Yes, exactly.

**Comment by dchertousov** [comment]
I believe constructor option is more convenient way.
Do you want to include it in 0.5.1?

We have plans to release it before wednesday afternoon.

**Comment by shmuga** [comment]
Ok, got it. Will finish till Wednesday.

**Comment by shmuga** [comment]
I think how it would be better to pass log function here.

https://github.com/Travelport-Ukraine/uapi-json/blob/1d65a22a4b2dacccca25cdb68393869aafed2ffe/src/Services/Air/AirParser.js#L326
