### ISSUE TITLE
Error during AirPrice request

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#63]
AirPrice returns next error when `ClassOfService` is avoided.
Handle error correctly and add `/AirPricingModifiers @InventoryRequestType="DirectAccess"` to avoid this error.

Remove `CheckOBFees="true"` from airPrice request because of next reason

> If you dont use payment by credit card inserted into reservation as Form of payment, some offers can be higher, because an airline wants to get additional money for payment gateway.

```xml
<?xml version="1.0" encoding="utf-8"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<SOAP:Fault>
			<faultcode>Server.System</faultcode>
			<faultstring>000276 BOOKING CLASS/PREFERENCE NOT AVAIL CHECK AVAILABILITY </faultstring>
			<detail>
				<common_v36_0:ErrorInfo xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0">
					<common_v36_0:Code>3319</common_v36_0:Code>
					<common_v36_0:Service>WEBSVC</common_v36_0:Service>
					<common_v36_0:Type>System</common_v36_0:Type>
					<common_v36_0:Description>Booking Class/Preference not avail, check availability.</common_v36_0:Description>
					<common_v36_0:TransactionId>1A87AD370A0759CB9292B9B095DA57CF</common_v36_0:TransactionId>
					<common_v36_0:TraceId/>
				</common_v36_0:ErrorInfo>
			</detail>
		</SOAP:Fault>
	</SOAP:Body>
</SOAP:Envelope>
```

**Comment by mbrandysky** [comment]
The error will still occur if the flight does not exist (as was the issue discussed through Skype).

**Comment by Smotrov** [comment]
https://github.com/Travelport-Ukraine/uapi-json/pull/67/files

**Comment by Smotrov** [comment]
https://github.com/Travelport-Ukraine/uapi-json/pull/67/files

**Comment by Smotrov** [comment]
https://github.com/Travelport-Ukraine/uapi-json/pull/67/files
