### ISSUE TITLE
TerminalService.createSession() throws "TypeError: Cannot read property 'uapi_version' of undefined" 

### ISSUE THREAD

**Issue by jirismika** [Travelport-Ukraine/uapi-json#65]
I was already working with TerminalService on monday, before the latest [commits](https://github.com/Travelport-Ukraine/uapi-json/commit/336ee0d18fb0d9d700243d323552a9613ea0af60), and it worked. Today, I've updated from upstream, run `npm run build` and now I got this error message:

> TypeError: Cannot read property 'uapi_version' of undefined
    at Parser.createSession (/home/smika/jobs/uapi-dev/uapi-json/build/Services/Terminal/TerminalParser.js:10:32)
    at tryCallOne (/home/smika/jobs/uapi-dev/uapi-json/node_modules/promise/lib/core.js:37:12)
    at /home/smika/jobs/uapi-dev/uapi-json/node_modules/promise/lib/core.js:123:15
    at flush (/home/smika/jobs/uapi-dev/uapi-json/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

I've checked the latest commits and found possible problem [there](https://github.com/Travelport-Ukraine/uapi-json/commit/336ee0d18fb0d9d700243d323552a9613ea0af60#diff-b90b95f6f34b2bc2ceefbfc63e93fa6dL13), as Babel transforms `this` to `undefined`.

Or am I doing something wrong?

**Comment by dchertousov** [comment]
Thank you for the report!
This might be a result of using arrow-functions for the parser. I've changed it in the latest commit to master.

Could you please test it and post a result here?

**Comment by jirismika** [comment]
Thank you for a quick fix, this is working now correctly.

**Comment by dchertousov** [comment]
Thank you.

**Comment by Smotrov** [comment]
https://github.com/Travelport-Ukraine/uapi-json/commit/27b504fc60f76b4fce52b2ffdf61a3974ae9600c
