### ISSUE TITLE
How do I log raw XMLs for certification purposes?

### ISSUE THREAD

**Issue by skills-up** [Travelport-Ukraine/uapi-json#654]
I'm planning to use this wrapper for the new version of my travel booking app, which currently uses SOAP via WSDL.

One of the certification requirements by Travelport is to submit XML logs for specified actions. Is this wrapper capable of generating raw XML logs? Or are there any methods available to get XML strings so that I can save them to a file myself?

**Comment by dchertousov** [comment]
Hi @skills-up !

There are some options for that.

First, there is `setting.debug: number` parameter, that will. ensure debugging if the many data including XML requests and responses as described [here](https://github.com/Travelport-Ukraine/uapi-json?tab=readme-ov-file#settings-object). It is enough to set it to `1` to get requests and responses logged.

By default, requests and responses will be logged with default logger, which is `console.log`.

If you want to change this behaviour,  you may pass your own log function in `settings.options.logFunction`.  All the requests start with `Request XML: ` prefix and all the responses with `Response SOAP: `. With your own logger, you may filter only requests and responses and log only them.
