### ISSUE TITLE
Provider Transaction Failed

### ISSUE THREAD

**Issue by skills-up** [Travelport-Ukraine/uapi-json#661]
Hello,

I keep getting the `Provider Transaction Failed` error on simple Low fare search request.

Request URI: `https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService`

Request XML:
```xml
<!--Release 33-->
<!--Version Dated as of 14/Aug/2015 18:47:44-->
<!--Air Low Fare Search For Galileo(1G) Request-->
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:LowFareSearchReq AuthorizedBy="user" TraceId="" TargetBranch="P7076434" ReturnUpsellFare="true"
      xmlns:air="http://www.travelport.com/schema/air_v52_0"
      xmlns:com="http://www.travelport.com/schema/common_v52_0">
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="DEL" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="BOM" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2024-07-08"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers MaxSolutions="100">
        <air:PreferredProviders>
          <com:Provider Code="1G"
            xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
        </air:PreferredProviders>
      </air:AirSearchModifiers>
      <com:SearchPassenger Code="ADT"
        xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
      <air:AirPricingModifiers CurrencyType="INR" />
    </air:LowFareSearchReq>
  </soap:Body>
</soap:Envelope>
```

Response XML:
```
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.System</faultcode>
      <faultstring>Provider transaction failed.</faultstring>
      <detail>
        <common_v52_0:ErrorInfo xmlns:common_v52_0="http://www.travelport.com/schema/common_v52_0">
          <common_v52_0:Code>700003</common_v52_0:Code>
          <common_v52_0:Service>SOASYSTEM</common_v52_0:Service>
          <common_v52_0:Type>System</common_v52_0:Type>
          <common_v52_0:Description>Provider transaction failed.</common_v52_0:Description>
          <common_v52_0:TransactionId>9184E1AD0A0D6A9316E27ACA3D1A17F9</common_v52_0:TransactionId>
          <common_v52_0:TraceId/>
        </common_v52_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope> 
```

Travelport support says it's working at their end using the same credentials. Could someone please help me understand and fix the issue?

I'm using v1.17.1 of the library

**Comment by frhnfrq** [comment]
Got the same issue. It's working with production credentials but not with pre production ones.

**Comment by dchertousov** [comment]
Hello!

If the same transaction works on production and does not work on pre-prod, it's likely not the `uapi-json` issue. Please contact TVPT support to address it.

**Comment by skills-up** [comment]
@dchertousov weren't you rather quick to close the issue?

I am facing the issue with the library, while the same credentials work with postman. Doesn't it mean the issue is with the library, while testing in pre-production? Or, you want to suggest to deploy it directly in production without testing in pre-prod first?

**Comment by dchertousov** [comment]
@skills-up
This library is merely a XML wrapper for the JSON data you provide.

Is your request in Postman and one, formed by the library the same? Is there any difference in headers?

**Comment by 63802654** [comment]
`<soap:Envelope
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:LowFareSearchReq
            AuthorizedBy="user" TraceId="XJ705928" TargetBranch="P7233909"
            ReturnUpsellFare="true"

      xmlns:air="http://www.travelport.com/schema/air_v52_0"

      xmlns:com="http://www.travelport.com/schema/common_v52_0"
            >
      <com:BillingPointOfSaleInfo OriginApplication="uAPI"/>
      <air:SearchAirLeg>
        <air:SearchOrigin>
          <com:CityOrAirport Code="HGH" PreferCity="true"/>
        </air:SearchOrigin>
        <air:SearchDestination>
          <com:CityOrAirport Code="MFM" PreferCity="true"/>
        </air:SearchDestination>
        <air:SearchDepTime PreferredTime="2025-04-23"/>
        <air:AirLegModifiers>
          <air:PreferredCabins>
            <com:CabinClass Type="Economy"/>
          </air:PreferredCabins>
        </air:AirLegModifiers>
      </air:SearchAirLeg>
      <air:AirSearchModifiers
                    MaxJourneyTime="48"
                    MaxSolutions="200"
            >
        <air:PreferredProviders>
          <com:Provider Code="1G"
            xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
          </air:PreferredProviders>
          <air:PermittedCarriers>
            <com:Carrier Code="MU"
              xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
              <com:Carrier Code="CZ"
                xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
              </air:PermittedCarriers>
            </air:AirSearchModifiers>
            <com:SearchPassenger Code="ADT"
              xmlns:com="http://www.travelport.com/schema/common_v52_0"/>
              <air:AirPricingModifiers
                CurrencyType="CNY"

                ETicketability="true"
            />
              <air:PCC>
                <com:OverridePCC ProviderCode="1G" PseudoCityCode="3CS6"/>
              </air:PCC>
            </air:LowFareSearchReq>
          </soap:Body>
        </soap:Envelope>
` This is the xml request, created by uapi-json

**Comment by skills-up** [comment]
@63802654 It seems that the issue occurs in interactive mode. However, as a script run with `node <script>` it works alright.
