### ISSUE TITLE
Error handling during AirCreateReservationReq

### ISSUE THREAD

**Issue by shmuga** [Travelport-Ukraine/uapi-json#68]
Example:
```xml
<?xml version="1.0" encoding="utf-8"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP:Body>
		<SOAP:Fault>
			<faultcode>Server.Business</faultcode>
			<faultstring>General air service Error.</faultstring>
			<detail>
				<air:AvailabilityErrorInfo xmlns:air="http://www.travelport.com/schema/air_v36_0" xmlns:common_v36_0="http://www.travelport.com/schema/common_v36_0">
					<common_v36_0:Code>3000</common_v36_0:Code>
					<common_v36_0:Service>AIRSVC</common_v36_0:Service>
					<common_v36_0:Type>Business</common_v36_0:Type>
					<common_v36_0:Description>General air service Error.</common_v36_0:Description>
					<common_v36_0:TransactionId>2EF06C7B0A0759BA9A84AEBBF738104B</common_v36_0:TransactionId>
					<common_v36_0:TraceId/>
					<air:AirSegmentError>
						<air:AirSegment Key="+oMVtgBAAA/BCOsaQAAAAA==" Group="0" Carrier="YE" FlightNumber="211" Origin="IEV" Destination="TBS" DepartureTime="2016-11-08T08:45:00.000+02:00" ArrivalTime="2016-11-08T12:30:00.000+04:00" ClassOfService="K" ChangeOfPlane="false" OptionalServicesIndicator="false"/>
						<air:ErrorMessage>*0 AVAIL/WL CLOSED*</air:ErrorMessage>
					</air:AirSegmentError>
				</air:AvailabilityErrorInfo>
			</detail>
		</SOAP:Fault>
	</SOAP:Body>
</SOAP:Envelope>
```

**Comment by mbrandysky** [comment]
This err *0 AVAIL/WL CLOSED* means that there is no available class which you requested for AirSegment air:AirSegment Key="+oMVtgBAAA/BCOsaQAAAAA==". Its not a bug and end user should be notified, or you can remove class (RBD) from the request and offer lower available class/price, if such behavior is requested.

**Comment by shmuga** [comment]
@mbrandysky That's not the request to you. But anyway thanks for help! This task is for me :)
I need just to handle this error correctly.

**Comment by articice** [comment]
@shmuga this error is now handled properly in [this new code](https://github.com/Travelport-Ukraine/uapi-json/pull/272/commits/df9c2e9fe51dc1586f493f3ed276d0141d241b14) from #267
There's a unit test in  that uses `Air/AirCreateReservation.Waitlist.xml` that shows this would throw AirRuntimeError.SegmentBookingFailed.

A similar case is the `Air/AirCreateReservation.Waitlisted.xml` which is the system's response for `restrictWaitlist`=true, it throws an AirRuntimeError.SegmentWaitlisted error for open/closed waitlists.

@Smotrov FYI
