### ISSUE TITLE
Pass pcc auth param as ticketingPcc book param

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#83]
I found `pcc` param from `auth` being used only in one transaction in AirService.
I propose to move it from auth to method option.
We should do it along with adding `overridePcc`, because having `pcc` and `overridePcc` in the same context may confuse users.

**Comment by dchertousov** [comment]
@articice according to [this](https://github.com/Travelport-Ukraine/uapi-json/pull/81#discussion_r93235956) discussion, could you please remove the pcc param?

**Comment by dchertousov** [comment]
@articice, @Smotrov , @shmuga  is it ok for me to tak this issue?

**Comment by Smotrov** [comment]
Ok

**Comment by dchertousov** [comment]
@Smotrov, @articice what do you think about the complete removing of the `pcc` param for `AirService` functions? At the time it's being used only to format output data. But caller of the function, created `AirService` object definitely knows what PCC he is going to use.

What do you think?

**Comment by dchertousov** [comment]
This will remove `pcc` input param and `pcc` from output format of search, book and other functions.
