### ISSUE TITLE
Canceling booking

### ISSUE THREAD

**Issue by Smotrov** [Travelport-Ukraine/uapi-json#84]
There is a need for method that will do a canceling of the existing bookings.
As usually it would be perfect to simplify an interface as it possible. I guess that one parameter _PNR number_ should be more then enough.

**Comment by Smotrov** [comment]
Canceling should be done [by PNR](https://support.travelport.com/webhelp/uapi/uAPI.htm#Booking/Cancel/Canceling_Bookings.htm).

**Comment by dchertousov** [comment]
@Smotrov I think we should check for open tickets before cancelling and if any return an `Error`

**Comment by dchertousov** [comment]
I propose following options for method:

```json
{
  pnr: 'PNR001',
  force: true
}
```

If `force` param passed and equals `true`, then uapi-json tries to cancel tickets.
If no `force` params or it doesn't equal `true`, then uapi-json throws an error if there are tickets with `OPEN` status.

**Comment by dchertousov** [comment]
@Smotrov , please confirm

**Comment by Smotrov** [comment]
Please use `cancelAllTicketsInPNR` instead of `force`.

**Comment by dchertousov** [comment]
Too long, may it be just, `cancelTickets` ?

**Comment by Smotrov** [comment]
Ок
