### ISSUE TITLE
Create shared validators and validation error classes

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#85]
We have a very flat and incoherent model of validators and validation errors.

- Validators like .locatorCode (check UR locator code) should be common for AirService and HotelsService.
- PaymentDataError.CvvMissing, PaymentDataError.CvvInvalid, PaymentDataError.ExpDateMissing, etc. should not be part of HotelsValidationError, they could be used in Air too
- TravellersError.AdultsMissing, TravellersError.ChildrenAgeInvalid and other traveler validation errors should not be part of HotelErrors.js:HotelsValidationError group only

some error classes can be duplicated to simplify the overall model, although code reuse in general should be encouraged more.

I suggest to:
- create a ServicesErrors file in Services folder, included from AirService/\*.js files (along with AirErrors.js) and HotelsService/\*.js (along with HotelsErrors.js) containing error classes with common function;
- a common ancestor class Validator for all services validators (i.e. AirValidator, HotelsValidator, etc.) containing shared validation functions (like locatorCode() for UR locators) for major validated entities.

This is an early step which doesn't quite conform with the [Rule of three](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)) but such transformation will eventually become necessary.

**Comment by shmuga** [comment]
In #146 provided functionality for shared validators. But we don't need them now so reopen ticket when someone will create shared validators.
