### ISSUE TITLE
Add getTicket method

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#86]
getTicket method should be added to AirService in order to provide detailed information about the ticket, as importuner method gives only ticket number.

**Comment by Smotrov** [comment]
Method should support PCC emulation (optionally)

**Comment by shmuga** [comment]
Is there any method in uapi that will resolve additional information?

**Comment by dchertousov** [comment]
Yes, it is called `AirRetrieveDocumentReq`.

**Comment by dchertousov** [comment]
Attached response example of the proposed getTicket output:
[getTicketResponse.json.txt](https://github.com/Travelport-Ukraine/uapi-json/files/719447/getTicketResponse.json.txt)

**Comment by Smotrov** [comment]
@dchertousov please remove all unnecessary keys from response.

**Comment by dchertousov** [comment]
Response has been updated:

[getTicketResponse.json.txt](https://github.com/Travelport-Ukraine/uapi-json/files/723658/getTicketResponse.json.txt)

**Comment by dchertousov** [comment]
@Smotrov , please check

**Comment by dchertousov** [comment]
`getTicket` method added with some limitations (see #114)
As this limitations are now a part of separate ticket, this one will be closed

**Comment by Smotrov** [comment]
Please update docs/examples.
