### ISSUE TITLE
Universal search for bookings & tickets

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#87]
We need to create universal `.search` method for `AirService` which will accept any string, and then will be able to return search results after performing following actions:
 - searching for PNR (if the string contains 6 alphanumeric characters)
 - searching for tickets, when string contains numbers, spaces and dashes only

**Comment by dchertousov** [comment]
We should think about the format of search results as this kind of request may return results of different types.

**Comment by Smotrov** [comment]
Lets call it `.searchBookings`.
To do not mix it up with shopping functions

**Comment by Smotrov** [comment]
Format should be simple (as we love to).
There should be only one input string parameter `searchPhrase`. 
Result should be an object that contains array of PNR's and array of warnings. 

Function should also have not mandatory emulation functional.

**Comment by dchertousov** [comment]
As we also search for tickets, I don't think that array of PNRs is enough :)

**Comment by shmuga** [comment]
I don't think that we even need such function if we have import by PNR and if we are going to implement this function https://github.com/Travelport-Ukraine/uapi-json/issues/86. 
Maybe it's better to have utils module that will export next functions:
- isTicket(ticket: string) -> boolean
- isPNR(pnr: string) -> boolean

So we'll receive simplicity over versatility.

**Comment by Smotrov** [comment]
If user will pass ticket number in `searchPhrase` function should return a PNR that contains this ticket anyway.

**Comment by dchertousov** [comment]
Well, it's not always possible.
At least in case, when booking is already archived, but ticket still exists.

**Comment by Smotrov** [comment]
Oh! Exactly! Then the second array should contain _ticketsWithArchvedBookings_

**Comment by dchertousov** [comment]
I propose just this:

```
{
  bookings: [
    // PNR list
  ],
  tickets: [
    // Tickets list
  ]
}
```

Each ticket will have corresponding pnr attribute

**Comment by Smotrov** [comment]
Please change `tickets` to `ticketsWithArchvedBookings`
Because if someone has passed ticket number as a parameter and this ticket has an active, retrievable booking in this cace the first array should contain booking number of this booking & second should be empty (or not exist at all).

**Comment by dchertousov** [comment]
I find it a little strange when someone enters ticket number, but receives a whole booking. In RDP, for instance, searching by ticket number opens a ticket and gives ability to void or refund it, as ticket is a separate object.

**Comment by dchertousov** [comment]
@Smotrov should it remain in the current milestone, or should we move it to 0.8.0?
Is search functionality is the one we need right now?

**Comment by Smotrov** [comment]
As you wish. 
Doesn't meter for me at all.

**Comment by shmuga** [comment]
Now we have importPNR / getTicket / searchBookingsByPassengerName
Do we still this universal function?

**Comment by dchertousov** [comment]
Removed from milestone as decided not to complete.
