### ISSUE TITLE
Fix for service error callbacks and versions usage in parsers

### ISSUE THREAD

**Issue by articice** [Travelport-Ukraine/uapi-json#95]
The flexibleVersions branch has an important fix for 
- using the recursive parser for SOAP error response callback parsers for each service
- using this->uapi_version in error callbacks

Note: Mark has added version auto-detect in case of errors, so this fix does not break hotels, which run on v34 (the rest is v36).

**Comment by dchertousov** [comment]
@shmuga, @articice  does it makes sense to move service version from parser itself to services (Air/Hotel/etc)?
It can save time for us not to upgrade Hotels to v36 and we will know how each service is going to work.

**Comment by dchertousov** [comment]
As @shmuga mentioned, parser auto detects uapi_version.

But are there any situations that can not be handled by this auto detector?

**Comment by articice** [comment]
@dchertousov Yes, it makes sense to configure each service with version number.

**Comment by articice** [comment]
@dchertousov The auto-detector only knows how to figure out version from SOAP:Fault answers.

It can not handle arbitrary replies. But the version number is also present in [request templates](https://github.com/Travelport-Ukraine/uapi-json/blob/4213cf7ed84197b9d8d0115847d682a876a1349e/src/Services/Hotels/templates/HOTELS_BOOK_REQUEST.xml#L5) (currently hardcoded into each template) and reply is expected to have objects only of this version, so it's not a problem and auto-detection is not needed.

We should make unitary configuration of used version (per service as you suggested) that will be inserted into request templates and expected in replies (set during parser construction).

**Comment by articice** [comment]
@shmuga did you ever get SOAP:Fault replies where replied objects version is different from requested?

**Comment by dchertousov** [comment]
According to discussion, decided to keep requests API version in templates only and parse version from responses.

**Comment by dchertousov** [comment]
What are we going to do if parser fails to detect version? Throw an error?

**Comment by shmuga** [comment]
@dchertousov I thinks yes. In this case we can detect error and than analyze it.

**Comment by dchertousov** [comment]
Ok

**Comment by dchertousov** [comment]
I have discovered several issues with removing manual version config, so #97 created to resolve them later.
